### ISSUE TITLE
R2DBC Statement.returnGeneratedValues(…) should retrieve generated keys on INSERT

### ISSUE THREAD

**Issue by mp911de** [jasync-sql/jasync-sql#105]
Calling `Statement.returnGeneratedValues(…)` should enable generated key retrieval for `AUTO_INCREMENT` columns.

**Comment by mp911de** [comment]
Wasn't able to directly figure out how this is supposed to work on MySQL.

**Comment by oshai** [comment]
There are a couple of alternatives here: https://github.com/jasync-sql/jasync-sql/wiki/FAQ#q-i-inserted-a-row-how-do-i-get-an-auto-incremented-id

Basically, it is returned from the server. Another option is to execute another query to get it.

**Comment by mirromutth** [comment]
It should be noted that `lastInsertId` query must be executed immediately after the INSERT statement, otherwise any other query *may* will cause `lastInsertId` query to produce unexpected results (maybe we need locks?). This logic also applies to `show warnings`.

**Comment by mirromutth** [comment]
@oshai I have a simple implementation: https://github.com/jasync-sql/jasync-sql/pull/108

**Comment by mirromutth** [comment]
`LAST_INSERT_ID()` return first generated value only after batch `INSERT`, should we return a `Flux` that is self-incrementing column from first id (call it `x`) to last id (that value must be `x + affectRows`)?

**Comment by oshai** [comment]
Fixed with #108 released in 0.9.33.
