### ISSUE TITLE
R2DBC implementation should use R2DBC exceptions

### ISSUE THREAD

**Issue by mp911de** [jasync-sql/jasync-sql#106]
Currently, exceptions are driver-specific (e.g. `com.github.jasync.sql.db.mysql.exceptions.MySQLException`). Once r2dbc/r2dbc-spi#53 is merged, we should make sure to use R2DBC-specific exceptions to give driver users a consistent experience regarding exceptions. This removes the need for driver-specific exception hierarchy handling in clients and applications.

**Comment by oshai** [comment]
@mp911de any idea when https://github.com/spring-projects/spring-data-r2dbc/issues/75 will be merged? Should I close this issue until then as well as https://github.com/r2dbc/r2dbc-spi/pull/53 ?

**Comment by mp911de** [comment]
I hope that the mentioned PR will be merged soon.

This ticket isn't implemented at all in `r2dbc-mysql` and closing it would lead to a false assumption. Right now, exceptions are jasync exceptions and not ones from the R2DBC hierarchy. Either implement a subtype of `R2dbcException` or (recommended) wait until the R2DBC Exception Hierarchy is in place to translate your exceptions in to more specific R2DBC exceptions.

**Comment by mp911de** [comment]
r2dbc/r2dbc-spi#47 is solved now, so you could take a look at this one.

**Comment by oshai** [comment]
@mp911de how can I depend on those changes (ie is it on a milestone or branch build and where can I find it)?

**Comment by mp911de** [comment]
Currently, all this is snapshots-only and we will release the next milestone in May.

**Comment by oshai** [comment]
I'm ok with using snapshots if you think that's the preferred approach at the moment. Just let me know how to use the snapshot.

**Comment by mp911de** [comment]
We're talking here about a balance. Snapshots are available now whereas a milestone would be available later. Snapshots are likely to change and could potentially break our build. I'd suggest to fix the issue on a branch and merge it later. R2DBC snapshots are published to https://repo.spring.io/snapshot.

**Comment by oshai** [comment]
fixed with #116
