### ISSUE TITLE
About implementation of r2dbc `Batch`

### ISSUE THREAD

**Issue by mirromutth** [jasync-sql/jasync-sql#110]
At the moment, `jasync` may not support executing a single query containing multiple statements. (to exchange multi-results)

@mp911de @oshai Could just support `Batch` that is a "fake" batch logic, execute multi-statements one-by-one? Like this: https://github.com/jasync-sql/jasync-sql/pull/109

**Comment by mp911de** [comment]
The SPI specifies mainly the intent to invoke certain things. `Batch` takes multiple simple SQL queries without binding and executes these. If MySQL or jasync do not support batch frames, then It should be fine to issue multiple regular queries (e.g. `List<String> sqlStatements` exected as`Flux.from(sqlStatements).flatMap(sql -> Mono.fromFuture(jasync.sendQuery(sql)).map(…))`)

The same approach should work with `Statement.add()` and multiple bindings.

**Comment by oshai** [comment]
I will merge #109 

Do you think there is a simple way to have the r2dbc tests in the module so we will make sure nothing gets broken?

**Comment by mp911de** [comment]
I would suggest in any case to add MockK tests, R2DBC Client has embedded test suites (see https://github.com/r2dbc/r2dbc-client/blob/master/src/test/java/io/r2dbc/client/MssqlExample.java for SQL Server). You can add these tests either to your project or submit a PR to R2DBC Client.

**Comment by mirromutth** [comment]
> The same approach should work with `Statement.add()` and multiple bindings.

@oshai I will submit a new PR to support `Statement.add()` later.

**Comment by oshai** [comment]
I added an example here: https://github.com/r2dbc/r2dbc-client/pull/46

Closing this issue.
