### ISSUE TITLE
mysql8 connect failed

### ISSUE THREAD

**Issue by imxingquan** [jasync-sql/jasync-sql#117]

**Comment by imxingquan** [comment]
io.netty.handler.codec.EncoderException: com.github.jasync.sql.db.exceptions.UnsupportedAuthenticationMethodException: Unknown authentication method -> 'caching_sha2_password'

**Comment by oshai** [comment]
That is probably a known compatibility issue with MySQL 8. To workaround that you can start MySQL server with `--default-authentication-plugin=mysql_native_password`.

Hope that helps.

**Comment by toxa108** [comment]
Had the same issue. I've just added to my /etc/mysql/my.cnf file:

```
[mysqld]
default-authentication-plugin=mysql_native_password
```

And restart mysql:
`sudo service mysql restart`
