### ISSUE TITLE
Regarding charsets and collations (default)

### ISSUE THREAD

**Issue by kartikone** [jasync-sql/jasync-sql#118]
Hi

I saw that there was recently a commit that changed the collation to utf8mb4_unicode_ci, from general_ci. I was wondering about how could it be changed to utf8mb4_0900_ai_ci? I was unable to use the flag -DjasyncMysqlUTF8Collation=255 to override this, and the current workaround I use is to Base64 encode and decode the columns that contain such characters.

**Comment by oshai** [comment]
Hi,
What version are you using? What do you mean by that it wasn't changed? Can you provide a test case?

**Comment by kartikone** [comment]
Hi, I'm using:
vertx-mysql-postgresql-client-jasync, version 3.7.0. If I understand correctly this is a vert.x implementation of your async driver, right? 

I have a column in a table that has the collation utf8mb4_0900_ai_ci, and certain characters (emojis) do not show up correctly at my end. I'm unable to determine a way to conclusively narrow down the issue, except for the fact that MySQL Workbench does display the value correctly (therefore the source is fine). The flow is as follows:

async driver -> query -> jsonarray -> print result in browser (content-type set correctly).

Additionally, the characters are replaced by ?, if that helps. 

Regards

Kartik Moudgil

**Comment by oshai** [comment]
First of all, make sure you're using the latest jasync (0.9.51) us the underlying layer by specifying in maven:
```
<dependency>
  <groupId>com.github.jasync-sql</groupId>
  <artifactId>jasync-mysql</artifactId>
  <version>0.9.51</version>
</dependency>
```
If that doesn't help we have a test case for similar issues:
https://github.com/jasync-sql/jasync-sql/blob/8e168f442b3175c102bdbeb8e6e706f24962fe8a/mysql-async/src/test/java/com/github/jasync/sql/db/mysql/QuerySpec.kt#L59

Probably just need to change the icon and mysql table settings.

**Comment by oshai** [comment]
I will also suggest to have a look at this wiki for more info: https://github.com/jasync-sql/jasync-sql/wiki/MySQL-Supported-Encoding

Let me know if that helps.

**Comment by kartikone** [comment]
Thanks oshai, I'll get back to you with the results

**Comment by kartikone** [comment]
I think updating to the latest underlying layer has fixed the issue, I will run a few more tests from my application and close the issue soon. Thanks for the help!
