### ISSUE TITLE
Timestamps decoded as org.joda.time.LocalDateTime

### ISSUE THREAD

**Issue by miguelaferreira** [jasync-sql/jasync-sql#120]
Thanks for this nice library, I've started to use it a few days ago and I'm quite happy with it. 
However, I'm facing some issues with the use of `org.joda.time.LocalDateTime`. Since `org.joda` basically became part of Java8 as `java.time` I would like to ask if there are any plans to migrate to `java.time` or if you would accept a PR that does that migration?

**Comment by oshai** [comment]
Thanks. Moving to Java 8 date time was planned. My main concern is backward comptability. I think there should be some sort of configuration to decide weather to use joda or not. A PR will be very welcome.

**Comment by oshai** [comment]
I am closing this issue, you're welcome to open a PR once you have some code and we will continue there the conversation.

**Comment by sysmat** [comment]
java.lang.ClassCastException: org.joda.time.LocalDate cannot be cast to org.joda.time.LocalDateTime

**Comment by sysmat** [comment]
You can't fetch Date as String and parse to Date.
So for Date column this is useless

**Comment by sysmat** [comment]
```java
row.getDate(1) -> produce error
(org.joda.time.LocalDate) row.get(2); -> work
```
To cast to gate Date column  from DB is very ugly

**Comment by oshai** [comment]
@sysmat I suggest to open another issue if you have a problem. Anyway, `LocalDate` and `LocalDateTime` are not the same thing (date vs date + time). try to use LocalDate itself.

**Comment by sysmat** [comment]
* API has only two methods for fetch Date and both return org.joda.time.LocalDateTime 
* I cast it to LocalDate  because in DB is only Date and not DateTime
* In mysql you have Date, DateTime, Time, Timestamp

**Comment by oshai** [comment]
@sysmat Regarding the cast: The driver itself is mainly pretty low level, but it's possible to add [here](https://github.com/jasync-sql/jasync-sql/blob/master/db-async-common/src/main/java/com/github/jasync/sql/db/RowData.kt) getLocalDateTime(col) and getLocalDate(col) if you want. Theoretically, we [plan](https://github.com/jasync-sql/jasync-sql/issues/131) to move to java 8 time so there is a sense to do it together, although I do not see it happen soon.
Regarding the type conversions for mysql see the types [here](https://github.com/jasync-sql/jasync-sql/wiki/MySQL-Types) with some comments below about the conversions.
