### ISSUE TITLE
Add support for connection initializer

### ISSUE THREAD

**Issue by mikx** [jasync-sql/jasync-sql#123]
For example: 

```
initSql = "SET TIME ZONE 'UTC'"
...
connectionFuture.thenComposeAsync { conn -> conn.sendQuery(initSql).thenApply (conn) }
...

```

**Comment by oshai** [comment]
Sounds like a good idea. would you like to contribute that?

**Comment by oshai** [comment]
BTW - without any modifications to the lib, its possible to override the relevant connection factory and execute the additional statement.

**Comment by mirromutth** [comment]
My personal opinion is that this should be something that the application-level framework should consider (such as ORM) rather than what the driver should contain.

**Comment by oshai** [comment]
I am closing it since there is a workaround for that and decided not to implement it at the moment.
