### ISSUE TITLE
publish to maven central instead of jcenter

### ISSUE THREAD

**Issue by xuwei-k** [jasync-sql/jasync-sql#127]

**Comment by oshai** [comment]
I understand this is more convenient, so will see how to add that. In the meanwhile, is there any limitation preventing you from using jcenter?

**Comment by xuwei-k** [comment]
https://central.sonatype.org/pages/requirements.html

> In addition we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.

**Comment by oshai** [comment]
I released 1.0.0 to maven-central, please check it works and let me know that I can close the ticket.

**Comment by aschlesener** [comment]
@oshai Is it possible to also add the 0.9.x versions to Maven Central? The latest version of `vertx-mysql-postgresql-client` still uses 0.9.51 of `jasync-mysql` and `jasync-postgresql`.

**Comment by oshai** [comment]
@aschlesener I can try to do that, but I suggest instead to upgrade explicitly to latest version of `jasync-sql` in your project configuration. There were no breaking changes when moving to 1.0 so it should work.
