### ISSUE TITLE
[R2dbc] Consider property `lastInsertId` of `OkMessage` to implement `returnGeneratedValues`

### ISSUE THREAD

**Issue by mirromutth** [jasync-sql/jasync-sql#128]
It is a same issue from https://github.com/mirromutth/r2dbc-mysql/issues/21.

`lastInsertId` is a property in `OkMessage` (server-side). After the client sends `INSERT` statement, it will be a generated value same as the value of `SELECT LAST_INSERT_ID()` result.

If last statement is not `INSERT`, this property will be 0 same as the value of `SELECT LAST_INSERT_ID()` result.

So, can just use `OkMessage.lastInsertId` in statement result to consider `returnGeneratedValues` implemented by the driver level, rather than `SELECT LAST_INSERT_ID()` which is the application level. This will improve the performance and *atomic* operation.

This is also more friendly to prepared statements because the prepared statements do **NOT** support batch statements which not like simple statements.

**Comment by oshai** [comment]
@mirromutth - any plan to contribute that addition?

**Comment by mirromutth** [comment]
@oshai I am writing the code of relevant with `returnGeneratedValues`, but the exact time is not clear (because of my work or other things), maybe next weekend.

**Comment by oshai** [comment]
Thanks!

**Comment by mirromutth** [comment]
@oshai I might want to set `com.github.jasync.sql.db.mysql.MySQLQueryResult` to `public` for get `MySQLQueryResult.lastInsertId`, or do you have a better idea?
