### ISSUE TITLE
R2DBC: Allow more type for JasyncInsertSyntheticRow

### ISSUE THREAD

**Issue by mirromutth** [jasync-sql/jasync-sql#137]
It was found in #135 , but it is another problem.

For now, `JasyncInsertSyntheticRow` allows only `Long`,  `Integer`, `Short`, `Byte`, `Float`, `Double`, `Character`, `BigDecimal` and `BigInteger` (without any primitive type).

That means, if user calls `get(Object)`, will get an exception which message is "unmatched requested type Object".

@set4812 I will submit a PR to fix the bug right away. @oshai And I will try add some unit tests for `JasyncInsertSyntheticRow` and `JasyncInsertSyntheticMetadata`.

**Comment by oshai** [comment]
released in 1.0.5

**Comment by set4812** [comment]
I will test it after work.

**Comment by set4812** [comment]
Still error:( There is way to decompile kotlin class in intellij? I want place break point for check what is going on.

**Comment by oshai** [comment]
Its possible to download sources and put it a break point in intellij.

**Comment by set4812** [comment]
Strange it's working without problems right now. Maybe i run server with old version package, before update complete.
