### ISSUE TITLE
Support Blob data

### ISSUE THREAD

**Issue by edeani** [jasync-sql/jasync-sql#139]
Hi.

I have some photos in my database mysql. I try to get them, but I don't know How map those values. Could you help me?

**Comment by oshai** [comment]
I would expect that to be mapped to a byte array. Can you please provide your table schema so it can be tested?

**Comment by edeani** [comment]
This is the structure:
CREATE TABLE `categoria` (
  `code` int(11) NOT NULL DEFAULT '0' COMMENT 'Código de la categoria',
  `name` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre de la categoria',
  `image` blob COMMENT 'Imagen de la categoria',
  `description` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'DEscripción o detalle de la categoria',
  PRIMARY KEY (`codigo`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;

**Comment by oshai** [comment]
As I mentioned before blobs are supported. In java it should be decoded as byte array. If you see an issue with that please report it.

**Comment by edeani** [comment]
Yes, you all right. I have used  `.getAs(index) as ByteArray,` and It's works. Thanks!!!
