### ISSUE TITLE
Disable Logging

### ISSUE THREAD

**Issue by callmephil1** [jasync-sql/jasync-sql#145]
I've looked around on both jasync and kotlin-logging.
I could be blind but is there anyway to completely disable all logging in jasync?

**Comment by oshai** [comment]
Hi,
Its possible to change the log level to None for the logger defined here: https://github.com/jasync-sql/jasync-sql/wiki/FAQ#q-how-can-i-see-the-message-begin-sent-and-received-between-the-driver-and-the-server
