### ISSUE TITLE
Executing arbitrary statements post-connection (Postgres)

### ISSUE THREAD

**Issue by akleiman** [jasync-sql/jasync-sql#146]
Hello

I've run into a situation where I'd like to run a prewarm query on a PG connection, but jasync doesn't seem to have a mechanism to do this. (I could do it manually if I wasn't using the connection pool).

It seems like the place to do this would be `PostgresSQLConnectionBuilder` and `PostgresSQLConnection`, close to where you set application name. Would you be open to a PR?

**Comment by oshai** [comment]
We had a similar request not so long ago: https://github.com/jasync-sql/jasync-sql/issues/123
There is also a workaround explained in that issue how to do that. 
From my perspective this is a valid contribution although some other contributors think this is out of scope for the driver.
Check the other issue and let me know what you think.

**Comment by oshai** [comment]
@akleiman - do you want to create a PR for that or the workaround is good enough?

**Comment by akleiman** [comment]
Hi, sorry, yeah, I looked into it and your workaround would work for me. I don't know if I agree that it's out of scope and would prefer to have it more explicitly but the workaround is clean enough that it's moot.
