### ISSUE TITLE
COPY FROM STDIN support

### ISSUE THREAD

**Issue by Globegitter** [jasync-sql/jasync-sql#148]
Looking at https://gist.github.com/valyala/ae3cbfa4104f1a022a2af9b8656b1131 and various other reports it seems that `COPY tableName FROM STDIN` is the fasted when it comes to inserting a lot of data to postgresql, but it requires support from the driver. As far as I can see this is not supported currently. Is there a chance though for this to be implemented?

**Comment by oshai** [comment]
Can you give more details on what exactly `COPY tableName FROM STDIN` means? Is it something on the Postgres client/server protocol?

**Comment by Globegitter** [comment]
Here is the documentation: https://www.postgresql.org/docs/current/sql-copy.html and example java usage I have found:

```
try (Connection conn = DriverManager.getConnection(connUrl, myUid, myPwd)) {
    long rowsInserted = new CopyManager((BaseConnection) conn)
            .copyIn(
                "COPY table1 FROM STDIN (FORMAT csv, HEADER)", 
                new BufferedReader(new FileReader("C:/Users/gord/Desktop/testdata.csv"))
                );
    System.out.printf("%d row(s) inserted%n", rowsInserted);
}
```

Not sure how exactly to answer that question to be honest. The way I understand it it is a command similar to `INSERT` just optimised in a different way. And since postgres will read from STDIN one has to be able to send that data to the server somehow.

**Comment by Globegitter** [comment]
But I am also happy to look more into it, how exactly this is implemented, etc.

**Comment by oshai** [comment]
Yes, if you can look more into it that will be great.
I am not sure how STDIN is helping performance as the data is sent over TCP anyway.

**Comment by Globegitter** [comment]
Here is another article comparing inserts vs `COPY FROM`: https://www.citusdata.com/blog/2017/11/08/faster-bulk-loading-in-postgresql-with-copy

And a bit more background: https://stackoverflow.com/a/46721665/2085007 (Only "Missing out on COPY optimisations" contains any interesting information) & https://wiki.postgresql.org/wiki/COPY

The section "Caveats with import" is probably the most interesting one in the wiki, it says:
```
COPY is not terribly smart or clever, in fact it is dumb and simple. Here are some problems you expect with copy:
...
while much faster than any other import path...
```

So it seems that is the primary reason `COPY` is faster than `INSERT`, because it has specific assumptions and does less checks.

Does that answer the question any better?

**Comment by Globegitter** [comment]
Oh yeah I also found this on the topic: https://www.postgresql.org/docs/devel/protocol-flow.html#PROTOCOL-COPY which talks about the technical implementation in a bit more detail
