### ISSUE TITLE
streaming / single row mode support

### ISSUE THREAD

**Issue by Globegitter** [jasync-sql/jasync-sql#149]
It would be great if it was possible to support streaming out results from postgresql as it has the potential to reduce memory usage and improve perfomance. libpq supports this as is documented here: https://www.postgresql.org/docs/current/libpq-single-row-mode.html and so do other libraries based on that. 

I am not sure how much effort it would requre but if it being based on `Flow` (https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html) that would probably be the most natural fit for the kotlin ecosystem.

**Comment by oshai** [comment]
That's a good idea. Unfortunately, I don't have the time to do that at the moment so any contribution is welcome. I suggest that as the other api's keep the library java-first and add `Flow` support on top of that.
