### ISSUE TITLE
Upgrade to R2DBC 0.8.0.RC1

### ISSUE THREAD

**Issue by mp911de** [jasync-sql/jasync-sql#152]
R2DBC 0.8.0.RC1 is [scheduled for the end of September](https://github.com/r2dbc/r2dbc-spi/milestone/6). It makes sense to take a look at most recent SPI snapshots to catch up with the SPI changes.

**Comment by oshai** [comment]
From briefly looking at the list of pull requests I haven't seen changes that requires something here to be changed, but I might have missed things.
Right now we compile against `0.8.0.M8`. Should that be changed or is it better to wait for the RC1?

**Comment by mp911de** [comment]
There are a couple of additions (Connection metadata, AutoCommit/getIsolationLevel, Statement.bind(String) instead of bind(Object), Row.get(String) and RowMetadata. getColumnMetadata(String/int)).

I think having at least a branch makes sense. Please also note that we introduced deprecated methods to simplify migration until we have an RC1 release.

**Comment by oshai** [comment]
Thanks for the info, I will create a branch. Can you please remind me how to depend on the snapshot build of the RC1?

**Comment by oshai** [comment]
@mp911de I have skipped directly to RC2, see the above PR.
