### ISSUE TITLE
Error future.map JVM Target  1.8

### ISSUE THREAD

**Issue by Moriand** [jasync-sql/jasync-sql#153]
Hi  when importing `import com.github.jasync.sql.db.util.map`, and use 

```kotlin
val mapResult: CompletableFuture<Any?> = future.map { queryResult ->
            val resultSet = queryResult.rows
            when{
                resultSet != null -> {
                    val row = resultSet.head
                    row(0)
                }else -> -1
            }
        }```

in `future.map` error  JVM target version acept 1.6

**Comment by oshai** [comment]
Are you using Java 1.6?

**Comment by Moriand** [comment]
> Are you using Java 1.6?

No, I use 1.8. By changing it to 1.6 the other libraries generate compatibility error

**Comment by oshai** [comment]
You can try solutions from here: https://stackoverflow.com/questions/48988778/cannot-inline-bytecode-built-with-jvm-target-1-8-into-bytecode-that-is-being-bui

Also try to build from command line.

If that not help, please provide more details about your build.

**Comment by Moriand** [comment]
> You can try solutions from here: https://stackoverflow.com/questions/48988778/cannot-inline-bytecode-built-with-jvm-target-1-8-into-bytecode-that-is-being-bui
> 
> Also try to build from command line.
> 
> If that not help, please provide more details about your build.
Tank you @oshai
