### ISSUE TITLE
Getting the result as a string

### ISSUE THREAD

**Issue by TheSilentPro** [jasync-sql/jasync-sql#165]
So im trying to get the string returned but idk how to do it?
I tried result.toString

`    public static String getGuildPrefix(Guild g) {
        CompletableFuture<QueryResult> result = connection.sendPreparedStatement("SELECT prefix FROM guilds WHERE (id='" + g.getId() + "')");
        return result.toString();
    }`

**Comment by oshai** [comment]
See the wiki for examples: https://github.com/jasync-sql/jasync-sql/wiki/Executing-Statements
