### ISSUE TITLE
Batch insert 

### ISSUE THREAD

**Issue by iLavryk** [jasync-sql/jasync-sql#166]
Imagine a task where we need to parse a file and put it into DB. The file is extremely big. 
So using simple jdbc the code looks like (pseudo code):

```
File file = ...;
Connection con = ...;
PrepareStatement st = con.getStatement("insert into person (name, surname) values (?, ?)");

while (String line = file.getLine() != null) {
   String[] person = parseLine(line);
   st.setString(1, person[0]);     st.setString(2, person[1]);
   st.addBatch();
   if (count++ % batchSize == 0) st.executeBatch();
}
```

So the code works perfectly, but the problem is the thread spent much time to wait IO.
The thing I only need is to put inserts into DB and don't wait for results. So i wrote code using javasync library.

```
ConnectionPool pool = PostgreSQLConnectionBuilder.createConnectionPool(config);

while (String line = file.getLine() != null) {
     String[] person = parseLine(line);
     pool.sendPreparedStatement(INSERT_SQL, List.of (parse[0],parse[1]))
}

connectionPool.disconnect().get();
```

I expect that in background all my inserts would be executed. But after 6M rows i got PoolExhaustedException. Then i looked into db, and found only 200 rows were inserted.

So please assist me to understand:
1) how can i configure batch execution?
2) how can I force sync queries to be flushed into DB without blocking main thread?

**Comment by oshai** [comment]
Batching is not supported in jasync. You cannot also force flushing the data.
What you can do is two things:
1. tweak pool configuration such as num of connections and queue size.
2. Chain calls on the callbacks so you limit the number of queries send simultaneously.
