### ISSUE TITLE
Postgres RowData::getDate(int x) DateTime cannot be cast to org.joda.time.LocalDateTime

### ISSUE THREAD

**Issue by alexmnyc** [jasync-sql/jasync-sql#171]
I have a timestamp column at index 4 in Postgres

when calling 
```
LocalDateTime dateTime = rowData.getDate(4);
```

I get the exception 

DateTime cannot be cast to org.joda.time.LocalDateTime

Looks like it happens for `timestampz` column type in Postgres only. `timestamp` column produces LocalDateTime and works using `rowData.getDate(4)` as expected

**Comment by oshai** [comment]
It looks like the column in postgres contains time zone so DateTime should be used. See more details about the difference here: https://chasethedevil.github.io/post/joda-localdatetime-vs-datetime/
