### ISSUE TITLE
[jasync-mysql] Does jasync handle allowMultiQueries for MySQL?

### ISSUE THREAD

**Issue by kjeet** [jasync-sql/jasync-sql#174]
Is this config parameter expected to work with the current jasync MySQL driver? I 'm convinced it was running before and it is referenced here MemSQLTest.java in this repo but new I think I was mistaken. I didn't see where in the source it's handled and it seems to go unused in assembleConfiguration().

If not I'd love to implement it for you, but a nudge in the right direction would help, thanks!

**Comment by oshai** [comment]
allowMultiQueries is not supported as you noticed and any contribution is welcome. From my initial checks the implementation is not trivial, I would start by understanding how the protocol works for such case and what is the differences from single query. you can take a look [here](https://dev.mysql.com/doc/internals/en/capability-flags.html#flag-CLIENT_PROTOCOL_41) for a start (look for the word multi).

When we understand that we can discuss how to implement that in the driver.

**Comment by kjeet** [comment]
Hm, your third link implies jasync is using the X Protocol but your first link is to the C/S one. If you're using the X protocol, a quick peek tells me a multi-statement doesn't exist because it isn't needed.

From link [1], COM_SET_OPTION, which enables/disables CLIENT_MULTI_STATEMENTS capability for the current connection [2], doesn't have an equivalent in the X Protocol. It seems like we can pipeline directly in the protocol [3] to solve the main use for `allowMultiQueries`, reducing network round trips.

[1]: https://dev.mysql.com/doc/internals/en/x-protocol-comparison-comparison-to-mysql-c-s-protocol.html 
[2]: https://dev.mysql.com/doc/internals/en/com-set-option.html
[3]: https://dev.mysql.com/doc/internals/en/x-protocol-use-cases-use-cases.html

**Comment by kjeet** [comment]
Now, digging a little more, I can't seem to tell if the X protocol can even run regular SQL queries ...

**Comment by oshai** [comment]
At the moment we don't use the x-protocol but the regular client-server protocol. I think I just sent you the wrong link. it should be this one: https://dev.mysql.com/doc/internals/en/client-server-protocol.html

**Comment by kjeet** [comment]
Interesting, I wonder if it would just be easier to implement X since the protos are all there. Are you aware of any drawbacks?

**Comment by oshai** [comment]
[Here](https://www.percona.com/blog/2019/01/07/understanding-mysql-x-all-flavors/) is a great explanation about the x protocol. From what I understand the two limitations are that it's available only since 5.7.12 (released in 2016) and until MySQL 8 it is not installed by default so it needs an additional administrative command. 
Other than that it sounds that the protocol is more advanced and even better for our needs in some cases.
