### ISSUE TITLE
Add support for unix domain socket

### ISSUE THREAD

**Issue by oshai** [jasync-sql/jasync-sql#175]
This will allow to connect to databases that requires unix socket connection like Google Cloud SQL.

**Comment by oshai** [comment]
see also this issue: https://github.com/spring-projects/spring-data-r2dbc/issues/192

**Comment by andy-yx-chen** [comment]
I created a PR https://github.com/jasync-sql/jasync-sql/pull/176 for this, however don't know how to update the tests to try the new change, if you happen to know how to do it quickly maybe you can add some tests

**Comment by oshai** [comment]
With mysql try to configure the socket. This might help: https://superuser.com/questions/1411402/how-to-expose-linux-socket-file-from-docker-container-mysql-mariadb-etc-to

**Comment by andy-yx-chen** [comment]
Thanks, will work on it tomorrow

**Comment by oshai** [comment]
Any update on this issue?

**Comment by oshai** [comment]
I am continuing the work on this in #319 so reopened the issue. 
Thanks @andy-yx-chen and @czp3009 for previous impl (that was not yet merge but part of the current effort) in #176 and #285.

In the api side the current PR adds `socketPath` to Configuration. I am thinking if this is the most clear approach as in this case host + port are redundant. 
Also the current impl fallback to host port in case of some problems (when fallback to nio) and maybe this should be made more explicit.

**Comment by oshai** [comment]
Implemented in 2.1.6. Thanks @andy-yx-chen and @czp3009!

**Comment by andy-yx-chen** [comment]
> Implemented in 2.1.6. Thanks @andy-yx-chen and @czp3009!

Thanks, this has been quite some time, it's great to see this is closed
