### ISSUE TITLE
Issue android 24 java.time.duration not found

### ISSUE THREAD

**Issue by edeani** [jasync-sql/jasync-sql#183]
Hi.

I'm getting this error in android 24. What jasync version can I use?
I read about this error, and It happends because android 24 doesn't have this library.

Thanks for your help

**Comment by oshai** [comment]
jasync is officially tested on java 8 jdk, not on Android.
I think it is possible to use ThreeTenBP and D8 to overcome that as described here: https://jakewharton.com/d8-library-desugaring/#apk-size-impact

**Comment by edeani** [comment]
Thanks for your answer. The library works fine with android >= 26. I'll read the article.
