### ISSUE TITLE
Add useSuspending to ConnectionPool for better Kotlin support

### ISSUE THREAD

**Issue by ilya40umov** [jasync-sql/jasync-sql#184]
The current implementation of `.use` method is based on `CompletableFuture` and is not Kotlin-friendly. Instead, I had to write my own implementation that looks more or less like this:
```
suspend fun <T, C : ConcreteConnection> ConnectionPool<C>.useSuspending(
    block: suspend (SuspendingConnection) -> T
): T {
    var exception: Throwable? = null
    val connection = take().await()
    try {
        return block(connection.asSuspending)
    } catch (e: Throwable) {
        exception = e
        throw e
    } finally {
        if (exception == null) {
            giveBack(connection).await()
        } else {
            try {
                giveBack(connection).await()
            } catch (closeException: Throwable) {
                exception.addSuppressed(closeException)
            }
        }
    }
}
```
However, unlike the already provided `.use` function, this implementation is not using `configuration.executionContext`. Not sure how much of a problem this is.
At any rate, it would be nice to have a similar API available for Kotlin users.

P.S. I initially started with r2dbc interface for jasync, but the code ends up bloated with all of the "await" statements...

**Comment by oshai** [comment]
Nice idea, I can check how to add that to the api. Have you seen the implementation of [inTransaction](https://github.com/jasync-sql/jasync-sql/blob/e9896d615b3b997ca0f05a67f21f6ab40f54bbaf/db-async-common/src/main/java/com/github/jasync/sql/db/SuspendingConnection.kt#L296)? It takes a bit different approach:
```
connection.use { concreteConnection ->
                val suspendingConnectionImpl = concreteConnection.asSuspending as SuspendingConnectionImpl
                val dispatcher = connection.configuration.poolConfiguration.coroutineDispatcher
                CoroutineScope(Job() + dispatcher).future {
                    suspendingConnectionImpl.concreteInTransaction(f)
                }
            }.await()
```

**Comment by oshai** [comment]
@ilya40umov would you like to add this as a PR?

**Comment by oshai** [comment]
@ilya40umov any update on this? would you like to add a PR?

**Comment by ilya40umov** [comment]
Hey, sorry for not being responsive. I'd definitely like to add a PR. Where would you recommend me to add this API? (e.g. as a member method of ConnectionPool vs as an extension function) As far as I can tell the API in `ConnectionPool` is Java-friendly and does not have a single suspending method.

**Comment by oshai** [comment]
Like you mentioned the pool api is java friendly, so it's better to have it as an extension method. Maybe in the file of SuspendingConnection ?

**Comment by ilya40umov** [comment]
@oshai I'm back to doing Kotlin more activelly and figured we could finally address this point.
Could you please take a look at https://github.com/jasync-sql/jasync-sql/pull/209 and tell me what you think?

**Comment by oshai** [comment]
Yes, I am looking at it.
