### ISSUE TITLE
Support for batch operations

### ISSUE THREAD

**Issue by ilya40umov** [jasync-sql/jasync-sql#185]
I know that currently jasync does not support batch operations, which is clearly stated in [Known-Issues](https://github.com/jasync-sql/jasync-sql/wiki/Known-Issues), and it's not like this topic has not been raised here before: https://github.com/jasync-sql/jasync-sql/issues/110 https://github.com/jasync-sql/jasync-sql/issues/166

However, while writing a part of a data pipeline in Kotlin, I ran into this problem as well, and would like to understand if it is possible somehow to entertain the idea of having more support for batch operations.

Some arguments for this are:
- r2dbc supports both [batch](https://r2dbc.io/spec/0.8.0.RELEASE/api/io/r2dbc/spi/Batch.html) operations and binding multiple rows to a prepared statement (using `add()` function), which gave me x10 worse performance (via r2dbc using jasync as the driver) as using StringBuilder to create batch SQL queries
- building batch queries with StringBuilder is not secure (instead there should be a way to run batch queries as a prepared statement with placeholders for the parameters)
- the library is not only used for creating REST API's (which rarely need to perform batch operations), but also other applications (like data pipelines) which, more often than not, end up in need of streaming big amounts of data into DB

P.S. If you are open to the idea, but don't have capacity to work on this change, please keep this issue open so that others may end up picking this up and contributing.

**Comment by oshai** [comment]
I am open to the idea, and can keep the issue open. However, implementing it requires substantial amount of work, and I am not sure an open issue will motivate someone to pick that issue up.

**Comment by oshai** [comment]
See also #174
