### ISSUE TITLE
Support for SQL Server

### ISSUE THREAD

**Issue by james-novino** [jasync-sql/jasync-sql#186]
Currently jasync-sql only supports Postgres and MySQL. I’m not that familiar with the internals in this library but the underlying driver of JDBC supports SQL Server. 

Are there planned changes to include support for other JDBC relational databases specifically SQL Server?

**Comment by oshai** [comment]
Every database implementation requires support to a different wire protocol. At the moment I don't have plans to add support to SQL Server or any other database. Of course other people are welcome to contribute that, but it will probably require substantial amount of work.
