### ISSUE TITLE
QueryInterceptor intercepts test query

### ISSUE THREAD

**Issue by wilsongee** [jasync-sql/jasync-sql#188]
The test query `SELECT 0` is being intercepted as both a prepared statement and a query.

It would be a nice to have if the test query was not intercepted, otherwise, our custom interceptors will need to build in logic to ignore it.

ConnectionFactory.kt@L82
```
            if (testCounter++.rem(2) == 0) {
                item.sendPreparedStatement("SELECT 0", emptyList(), true).map { item }
            } else {
                item.sendQuery("SELECT 0").map { item }
            }
```

**Comment by oshai** [comment]
@wilsongee thanks for raising the issue.
Changing it is pretty simple.
The only question arise is are there cases that this is helpful?
Can you describe in more details why do you want to bypass the interceptors in that case?

**Comment by wilsongee** [comment]
We're doing request-level tracing and I'm in the middle of figuring out if we can take advantage of the interceptors to do it.

At the minimum, allowing the ability to disable intercepting of test queries would be nice and a good compromise.

**Comment by oshai** [comment]
It will be good to know if there are any other issue with tracing and how much the current issue is an obstacle. It might be helpful enough just to wrap the connection factory and call sendXXdirect method instead. If that's not helpful enough we can add configuration for it.

**Comment by oshai** [comment]
@wilsongee is the workaround good enough or do you still need the support for disable?

**Comment by wilsongee** [comment]
Hi @oshai,

Sorry, I have been working on other higher priority items and this fell off my plate. The PR looks good, but I think having configurations to disable would be best long term so that you preserve backwards compatibility and it allows someone like me to disable intercepting test queries. I would defer to you on what you think the default behavior should be.
