### ISSUE TITLE
MysqlConnectionFactoryProvider does not support queryTimeout

### ISSUE THREAD

**Issue by DerekKo82** [jasync-sql/jasync-sql#193]
https://github.com/jasync-sql/jasync-sql/blob/master/r2dbc-mysql/src/main/java/MysqlConnectionFactoryProvider.kt

Could you add queryTimeout field into configuration mapping?

**Comment by oshai** [comment]
AFAICT Query timeout is not part of r2dbc spi in ConnectionFactoryOptions, so it cannot be supported. Please correct me if I am wrong.

**Comment by DerekKo82** [comment]
Yes, query time is not part of r2dbc spi in ConnectionFactoryOptions. But we can make custom option like APPLICATION_NAME. So I request it.
Is there any other reason you didn't add the query timeout?

**Comment by oshai** [comment]
No, there is no other reason. I will add that.
