### ISSUE TITLE
Extract pooling

### ISSUE THREAD

**Issue by zapodot** [jasync-sql/jasync-sql#198]
The pooling mechanism implemented in jasync-common is really quite general and may be used for so much more than just database connection pooling. As an example we are using it to pool SFTP connections in one of our applications with great success so far ;-)

Have you considered extracting this functionality to a separate project?

**Comment by oshai** [comment]
Will having it as a separate module and artifact be enough? Moving to external project feels like an overkill.

**Comment by zapodot** [comment]
Sure! Whatever is easiest for you!



tir. 12. mai 2020, 19:50 skrev Ohad Shai <notifications@github.com>:

**Comment by oshai** [comment]
I separate it in 1.1.0 and added some details here: https://github.com/jasync-sql/jasync-sql/wiki/Object-Pool

**Comment by zapodot** [comment]
Nice!

Thank you 👍👍👍

tir. 19. mai 2020, 20:49 skrev Ohad Shai <notifications@github.com>:
