### ISSUE TITLE
Support for setting isolation level for DB/DBConnection

### ISSUE THREAD

**Issue by KevinAtSesam** [jasync-sql/jasync-sql#212]
Would it be interesting to implement a spacial pass-through parameter to set an isolation level for a transaction? Right now, it's possible to set an isolation level in scalikejdbc, but scalikejdbc-async misses this feature.

I haven't given much thought about the impact of this in an async setting, so please tell me if there are any unforeseen issues with such an addition.

### Background details 
- Implementation in scalikejdbc
  - https://github.com/scalikejdbc/scalikejdbc/issues/442
- Background info for databases
  - https://mariadb.com/kb/en/mariadb-transactions-and-isolation-levels-for-sql-server-users/
  - https://www.postgresql.org/docs/current/transaction-iso.html

### Context
I initially asked about this over at [scalikejdbc-async](https://github.com/scalikejdbc/scalikejdbc-async/issues/102) but it seems that supporting isolation levels is a multi-stage project.

**Comment by oshai** [comment]
If I understand correctly from the driver point if view setting isolation level is just another query to the db. How would you like to see that implemented? As another param to [this method](https://github.com/jasync-sql/jasync-sql/blob/3ead88254d623256d24102e8bca12787bd53d778/db-async-common/src/main/java/com/github/jasync/sql/db/Connection.kt#L190)?

**Comment by KevinAtSesam** [comment]
I think that would make most sense. 

We currently work around the issue by manually starting a transaction, then setting the isolation level, and then executing further queries, but it would be nice if it could be combined. This will also make is less ambiguous, because right now there is not really anything guiding users.

**Comment by oshai** [comment]
ok. would you like to create a pull request for that?
