### ISSUE TITLE
Support client SSL (mutual auth)

### ISSUE THREAD

**Issue by rockwotj** [jasync-sql/jasync-sql#213]
Right now ssl config allows for a cert from the server and sslmode, but doesn't support the client authenticating via a cert and private key. Some db configurations require the client to authenticate as well

**Comment by rockwotj** [comment]
I am happy to provide a PR for postgres, but I don't know anything about MySQL.

**Comment by oshai** [comment]
Thanks! a PR for postgres is welcome. Someone else might pick mysql up in the future.
