### ISSUE TITLE
Use of ? in quotes in a prepared statement

### ISSUE THREAD

**Issue by dave08** [jasync-sql/jasync-sql#217]
Currently Jasync doesn't differentiate whether `?` is within quotes or not. So when using ? inside quotes, it counts them as required parameters and throws an `InsufficientParametersException`. This doesn't let the user use ? in regexs and literal strings.

**Comment by oshai** [comment]
Try escaping with double question mark `??`. It should work, see also https://github.com/jasync-sql/jasync-sql/issues/196 and https://github.com/jasync-sql/jasync-sql/blob/9c6fa7cd145483ebd74beb4bd1f0707542c8e9c9/postgresql-async/src/main/java/com/github/jasync/sql/db/postgresql/PreparedStatementHolder.kt#L23
