### ISSUE TITLE
check postgres ssl and kerberos tests

### ISSUE THREAD

**Issue by oshai** [jasync-sql/jasync-sql#22]
were ignored when converted: https://github.com/jasync-sql/jasync-sql/commit/e4659459332bc20f385f91d783db43bcf578f8fa

This is the original ssl commit: 
https://github.com/mauricio/postgresql-async/commit/0f9a587ec3a9cd372f0b37f069848201236d2acf

**Comment by oshai** [comment]
@andy-yx-chen any chance you can help with this?

**Comment by andy-yx-chen** [comment]
@oshai, sure, I will take a look, but may require one or two weeks, as currently I am a bit busy on other stuffs.

**Comment by oshai** [comment]
Thanks! Its not urgent.

**Comment by andy-yx-chen** [comment]
just have time to start looking at this, it looks like just a matter of docker image configuration, the server key and crt are not picked up by the server, as well as the pg_hba.conf

**Comment by andy-yx-chen** [comment]
will try to see if we need to derive specific docker image for this project or not, sounds like not a bad idea to have a delicate Postgres docker image for this project to test

**Comment by oshai** [comment]
Thanks! I think it might be also possible to configure the image when it is started using test-containers:  https://www.testcontainers.org/features/commands/

**Comment by andy-yx-chen** [comment]
Kerberos is not something that the docker image supported (need a custom postgresql build), the only thing that the test covers is to report error if an authentication method is not supported (so far, only md5 and cleartext are supported), so let the kerberos test  stays as ignored, enable all ssl related tests in #100
