### ISSUE TITLE
could pass parameters into a in query?

### ISSUE THREAD

**Issue by MarchLiu** [jasync-sql/jasync-sql#221]
are there some way to set a dataset range of query like this?

```
select parent_id from tag where id in (?)
```

project use java8 and mysql 5.7

**Comment by MarchLiu** [comment]
I read the document https://github.com/jasync-sql/jasync-sql/wiki/MySQL-Types , but where are nothing about pass a collection .
So I could use in query in jasync?

**Comment by oshai** [comment]
It's not possible to do it with prepared statement, only with query without parameters.

**Comment by MarchLiu** [comment]
thx for help
