### ISSUE TITLE
Query timeout is not respected when host is not listening

### ISSUE THREAD

**Issue by ilya40umov** [jasync-sql/jasync-sql#223]
`com.github.jasync-sql:jasync-postgresql:1.1.6`

Steps to reproduce:
* Set up a connection pool with connection & query timeout (100ms in my case)
* Stop the server the client is pointing at
* Run the provided code

Observed behavior: only 1 exception (this number depends on `maxActiveConnections`, e.g. if I set it to 5, I will likely get 5 exceptions in the output) is printed out and the rest of the coroutines freeze, until the server is back up (easy to test by stopping and starting a container that is running Postgres).

Expected behavior: the client should respect the configured query / connection timeouts and throw an error back to the caller

Known workarounds: surround each call to the client with `withTimeout()`, but it's not clear if there are any side-effects to this solution

```
runBlocking {
    (1..50).map {
        GlobalScope.launch {
            try {
                println("Before SELECT 1")
                connectionPool.sendQuery("SELECT 1").await()
                println("After SELECT 1")
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }
    }.joinAll()
}
```

```
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:15432
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:673)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:650)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:530)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
```

**Comment by oshai** [comment]
Thanks for reporting!
It will be very helpful if you can check if that is a coroutines issue, or pool related issue by using threads instead of coroutines.
In addition trace logging will also be helpful and sharing the pool configuration (how did you set the timeout).

**Comment by ilya40umov** [comment]
This gives me pretty much the same behavior:
```
val executor = Executors.newFixedThreadPool(50)
(1..50).map {
    executor.submit {
        try {
            println("Before SELECT 1")
            connectionPool.sendQuery("SELECT 1").get()
            println("After SELECT 1")
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
}
executor.shutdown()
executor.awaitTermination(5, TimeUnit.MINUTES)
```

**Comment by ilya40umov** [comment]
This is how I'm creating the pool:
```
database:
  host: hostname
  port: 5432
  database: dbname
  username: user
  password: password
  maxActiveConnections: 5
  connectionTimeout: 100ms
  queryTimeout: 100ms

data class DatabaseConfig(
    val host: String,
    val port: Int,
    val database: String,
    val username: String,
    val password: String,
    val maxActiveConnections: Int,
    val connectionTimeout: Duration,
    val queryTimeout: Duration
)

fun DatabaseConfig.asPoolConfigBuilder(): ConnectionPoolConfigurationBuilder =
    ConnectionPoolConfigurationBuilder(
        host = host,
        port = port,
        username = username,
        password = password,
        maxActiveConnections = maxActiveConnections,
        database = database,
        connectionCreateTimeout = connectionTimeout.toMillis(),
        connectionTestTimeout = connectionTimeout.toMillis(),
        queryTimeout = queryTimeout.toMillis()
    )

val poolConfig = config.database.asPoolConfigBuilder().build()
PostgreSQLConnectionBuilder.createConnectionPool(poolConfig)
```

**Comment by ilya40umov** [comment]
[query_timeout_log.txt](https://github.com/jasync-sql/jasync-sql/files/5924640/query_timeout_log.txt)

**Comment by ilya40umov** [comment]
So while it's stuck, I see lots and lots of these messages printed in the log: 
```
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - scheduleNewItemsIfNeeded - availableItems=0 waitingQueue=45 inUseItems=0 inCreateItems=4 ActorCoroutine{Active}@6ef6ffa2
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - createObject createRequest=822
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - scheduleNewItemsIfNeeded - creating new object ; availableItems=0 waitingQueue=45 inUseItems=0 inCreateItems=5 ActorCoroutine{Active}@6ef6ffa2
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - received message: Created: createRequest=818 -> object=failed ; availableItems=0 waitingQueue=45 inUseItems=0 inCreateItems=5 ActorCoroutine{Active}@6ef6ffa2
10:30:13 [DefaultDispatcher-worker-1] DEBUG com.github.jasync.sql.db.pool.ActorBasedObjectPool - failed to create connection, with no callback attached 
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - scheduleNewItemsIfNeeded - availableItems=0 waitingQueue=45 inUseItems=0 inCreateItems=4 ActorCoroutine{Active}@6ef6ffa2
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - createObject createRequest=823
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - scheduleNewItemsIfNeeded - creating new object ; availableItems=0 waitingQueue=45 inUseItems=0 inCreateItems=5 ActorCoroutine{Active}@6ef6ffa2
10:30:13 [DefaultDispatcher-worker-1] TRACE com.github.jasync.sql.db.pool.ActorBasedObjectPool - received message: Created: createRequest=819 -> object=failed ; availableItems=0 waitingQueue=45 inUseItems=0 inCreateItems=5 ActorCoroutine{Active}@6ef6ffa2
10:30:13 [DefaultDispatcher-worker-1] DEBUG com.github.jasync.sql.db.pool.ActorBasedObjectPool - failed to create connection, with no callback attached 
```

**Comment by oshai** [comment]
Thanks for the details, very helpful!
I think I know what is the issue.
The timeout mechanism works on the query itself, not on waiting in the queue to get a connection.
We don't have a mechanism to timeout waiting futures.
The main thing I am trying to think right now is if we need another timeout configuration for that or we can use one of the existing: `connectionCreateTimeout`, `connectionTestTimeout`, `queryTimeout`.

I am thinking of reusing one of them, maybe the `queryTimeout` because this is the time the user is willing to wait.
Although, for simplicity we will not accumulate the wait+query so for some edge cases you might timeout only after double of that time.

**Comment by ilya40umov** [comment]
@oshai overall, I'll be happy if it times out at all. :) 
In this particular case I would probably expect it to fail after `connectionCreateTimeout` passes (as internally the driver is trying to establish a connection) and get a Connect exception of some sort. But if worse comes to worst, it's also okey to get a response back after `queryTimeout` (or even `queryTimeout + connectionCreateTimeout`) and a Query timeout exception of some sort.

Also, my testing is showing me that even if I use `connectionPool.sendQuery("SELECT 1").get(5L, TimeUnit.SECONDS`, I'm still seeing queries in the queue `availableItems=0 waitingQueue=45 inUseItems=0 inCreateItems=5` which already timed out. So, I'm concerned that those queries will pipe up in the real live use-cases. Do you happen to know if the driver will discard those queries when the db is back up? Or it will try to run all of the queries that get queued (even though the client is not waiting for them to finish)?

**Comment by oshai** [comment]
What I will use for timeout is the `queryTimeout`. Adding a timeout for the waiting futures will operate in two cases that I can think of:
- server is down
- pool is exhausted: this will happen when many futures are waiting in queue  

I think that because of the second scenario we need a bigger timeout, which is probably the `queryTimeout`.

>Do you happen to know if the driver will discard those queries when the db is back up? Or it will try to run all of the queries that get queued (even though the client is not waiting for them to finish)?  

As for your question, I think such timeout is good only as a workaround as it will keep those queries in the queue.

I am starting to implement that, will update when I have something working that can be tested as a snapshot.
