### ISSUE TITLE
Misspelling tag `async-jdcb` in the "About"

### ISSUE THREAD

**Issue by rim99** [jasync-sql/jasync-sql#224]
A minor one. 

I think it should be `async-jdbc`.

**Comment by oshai** [comment]
Can you share an screenshot or a link where it is exactly?

**Comment by rim99** [comment]
![截屏2021-02-11 下午8 52 11的副本](https://user-images.githubusercontent.com/13381463/107638978-43f0e400-6cab-11eb-9385-9e36de183c64.png)

At the front page of this repo

**Comment by oshai** [comment]
Thanks, I fixed it.
