### ISSUE TITLE
PostgreSQLConnectionFactory logs eintire db configuration including password

### ISSUE THREAD

**Issue by mrayne** [jasync-sql/jasync-sql#226]
The PostgreSQLConnectionFactory the entire config on DEBUG level:

```
    init {
        logger.debug { "PostgreSQLConnectionFactory created with configuration $configuration" }
    }
```

Either the toString function should possibly be overwritten to not log sensitive data or the log message should be removed. A workaround would be to create your own connection factory class.

**Comment by oshai** [comment]
Thanks for reporting. I will change that although it's only in debug level.
