### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by anmol27katyani** [jasync-sql/jasync-sql#236]
I am using ```R2dbcEntityTemplate``` using R2dbcEntityTemplate , Any fix/suggestion is appreciated.

**Comment by anmol27katyani** [comment]
detailed message says "Failed to obtain R2DBC connection"

**Comment by oshai** [comment]
This exception `Thrown to indicate that the IP address of a host could not be determined.` ([link](https://docs.oracle.com/javase/7/docs/api/java/net/UnknownHostException.html))

What is the hostname you're trying to call? Is it reachable?
