### ISSUE TITLE
MySQL 8.0 connect failed.

### ISSUE THREAD

**Issue by whutjs** [jasync-sql/jasync-sql#239]
io.netty.handler.codec.EncoderException: com.github.jasync.sql.db.exceptions.UnsupportedAuthenticationMethodException: Unknown authentication method -> 'caching_sha2_password'

Do you plan to fix this issue? For users who cannot modify the mysql server, this issue block them from using this lib.

**Comment by oshai** [comment]
Thanks for reporting. For workarounds see: https://github.com/jasync-sql/jasync-sql/issues/117

But as you mentioned, I guess you can't / don't want to modify the server. At the moment I don't have plans to implement that but of course PR is welcome.

**Comment by Tuegor** [comment]
And I have modified MySQL Server options and have checked in Workbench that the option from mentioned issue was applied (the value now is caching_sha2_password) and still I keep receiving this crappy message. What's going on?
