### ISSUE TITLE
Can't connect to MySQL 5.7 

### ISSUE THREAD

**Issue by Noe-Garcia** [jasync-sql/jasync-sql#241]
Hello, Im looking for use the driver, but it gave me this issue
`
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.RuntimeException: Failed to load driver class com.mysql.jdbc.Driver in either of HikariConfig class loader or Thread context classloader
`

I include the driver on the build.gradle
```groovy
dependencies {
    driver 'com.github.jasync-sql:jasync-mysql:1.2.2'
}
```
And also in HikariConfig
```xml
<property name="driverClassName" value="${DRIVER_VARIABLE}" /> 
```
docker compose
```yml
environment:
      - DRIVERCLASS_NAME=com.mysql.jdbc.Driver
      - PROTOCOL=jdbc
      - SUB_PROTOCOL=mysql
      - DRIVER_VARIABLE=com.mysql.jdbc.Driver
```
what am I doing wrong?
Thanks everyone!

**Comment by oshai** [comment]
I think you have some kind of confusion. Hikari cannot be used with jasyc as jasync driver is not jdbc compliant.

If you want to work with Hikari, use jdbc driver, or alternatively use jasync implementation of connection pool with jasync.

**Comment by Noe-Garcia** [comment]
Alright got it, thank you!
