### ISSUE TITLE
In r2dbc-mysql, the prepared statement doesn't seem to be released

### ISSUE THREAD

**Issue by davidsun** [jasync-sql/jasync-sql#244]
https://github.com/jasync-sql/jasync-sql/blob/master/r2dbc-mysql/src/main/java/JasyncStatement.kt#L87

**Comment by hongjunan** [comment]
any progress in here?
i have same issue.
`Can't create more than max_prepared_stmt_count statements (current value: 16382);`

r2dbc-mysql does not release
`https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_prepared_stmt_count`

**Comment by oshai** [comment]
as a workaround you can try to see if the pool has something like maxConnectionTtl. Many pools have that. Usually prepared statement and not closed as they are use for cache between queries to improve efficiency.
