### ISSUE TITLE
Connection Pool is freezing after error 1205 lock wait timeout

### ISSUE THREAD

**Issue by Igorut** [jasync-sql/jasync-sql#245]
I met an incomprehensible behavior of the connection pool, if you asynchronously execute several requests in different transactions on the same row

![Screenshot from 2021-08-18 13-36-45](https://user-images.githubusercontent.com/24738632/129884483-67a03585-d968-426d-b6c8-f31e18c0877c.png)

Then after 60 seconds the following error appears

![Screenshot from 2021-08-18 13-37-37](https://user-images.githubusercontent.com/24738632/129884431-3ae586e0-f429-475e-9b16-46703f2deb87.png)

And any other requests will not be executed until the server is restarted :( What should I do with this?

MySQL version 8.0.26
Micronaut version 2.5.8
JAsync MySQL version 1.2.1

**Comment by Igorut** [comment]
MySQL version 8.0.26
Micronaut version 2.5.8

**Comment by Igorut** [comment]
I've found that some server threads stuck in the epoll_wait process

**Comment by Igorut** [comment]
I believe that the problem is related to the release of the coroutine or something like that, because the micronaut server is just running and does not respond to any request, so this means that the main thread is busy

**Comment by oshai** [comment]
Can you check what version of coroutines you're using? maybe try to use the latest?

**Comment by oshai** [comment]
Actually, this looks unrelated. Try the advices here: https://stackoverflow.com/questions/5836623/getting-lock-wait-timeout-exceeded-try-restarting-transaction-even-though-im
