### ISSUE TITLE
How to set different queryTimeout for each connection in a connection Pool ?

### ISSUE THREAD

**Issue by pagarwal-ignitetech** [jasync-sql/jasync-sql#253]
I am using latest jasync-sql with postgress
`    private val readPool = ConnectionPool(factory = PostgreSQLConnectionFactory(readInstanceConfiguration), configuration = poolConfiguration)
`
Now I want to run one connection at different queryTimeout than what is defined in pool configuration is it possible?

**Comment by oshai** [comment]
I think the best option is to create another connection outside of the pool.
