### ISSUE TITLE
Add PostgreSQL Schema support

### ISSUE THREAD

**Issue by Yomanz** [jasync-sql/jasync-sql#258]
Add PostgreSQL schema support to the library.

It's `search_path` in the actual data you send to postgres.

I'll try and PR this soon but I'm not used to Kotlin.

**Comment by Yomanz** [comment]
Not stale, see https://github.com/jasync-sql/jasync-sql/pull/259

**Comment by Yomanz** [comment]
Please open this again

**Comment by oshai** [comment]
if it will continue like that I will suspend the bot ;-)

**Comment by Yomanz** [comment]
> if it will continue like that I will suspend the bot ;-)

I believe if you assign the issue to someone it wont do that.

**Comment by oshai** [comment]
let's see. I assigned it to myself.

**Comment by Yomanz** [comment]
@oshai :(

**Comment by Yomanz** [comment]
@oshai Please open this again.
