### ISSUE TITLE
postgresql-async test suite doesn't have connection configurability

### ISSUE THREAD

**Issue by rafiss** [jasync-sql/jasync-sql#264]
Currently, [ContainerHelper](https://github.com/jasync-sql/jasync-sql/blob/master/postgresql-async/src/test/java/com/github/aysnc/sql/db/integration/ContainerHelper.kt) uses a hardcoded port, address, and username.
```
    /**
     * default config is a local instance already running on port 15432 (i.e. a docker postgresql)
     */
    var defaultConfiguration = Configuration(
        "postresql_async",
        "localhost",
        15432,
        "root",
        "netty_driver_test"
    )
```

I'd like to make these configurable so that I can run tests against a different instance. I was thinking that this could be changed to get these values from environment variables (like PGPORT, PGUSER, PGHOST -- see https://www.postgresql.org/docs/9.1/libpq-envars.html), and if the environment variables are not set, to use the existing hardcoded defaults. If you're open to the change, I can go ahead and submit a PR.

Background: I work on CockroachDB, which is wire-compatible with PostgreSQL. I'm interested in running the tests against CockroachDB (in the CockroachLabs CI system).

**Comment by oshai** [comment]
Hi,
A PR is welcome. Sounds like a reasonable change.
