### ISSUE TITLE
Make PostgreSQLColumnEncoderRegistry/PostgreSQLColumnDecoderRegistry extensible

### ISSUE THREAD

**Issue by dvilker** [jasync-sql/jasync-sql#275]
Now, to add processing of your own type (e.g., enumerations that are reflected in enumerations in the database), you will have to completely rewrite these classes.

And if the decoder can still be wrapped, the encoder will have to be rewritten significantly, because of the processing of arrays.

**Comment by oshai** [comment]
can you give more details about the db type and how it's transferred over the wire for such use case?

**Comment by oshai** [comment]
@dvilker - any update on the issue?

**Comment by oshai** [comment]
as part of #327 I plan to implement it. The api is going to be:
```
// decoder
PostgreSQLColumnDecoderRegistry.Instance.registerDecoder(type, decoder)
// encoder 
PostgreSQLColumnEncoderRegistry.Instance.registerEncoder(class, type, encoder)
```

**Comment by oshai** [comment]
Added in 2.1.7
