### ISSUE TITLE
Ability to get SQLSTATE from Postgres GenericDatabaseException

### ISSUE THREAD

**Issue by afbarbaro** [jasync-sql/jasync-sql#277]
I'm working on some application code that may need to retry an operation if certain error kinds are thrown by the Postgres database server while executing the query (for example, we may want to retry if the SQLSTATE is 55P03 (lock_not_available)). 

I don't see a way of precisely getting the SQLSTATE field out of the exception without hardcoding the `"SQLSTATE"` key as a string.   Here's my workaround code, that I'd like to get rid of:  

```
    private fun getSQLState(error: GenericDatabaseException): String? {
        val errorMessage = error.errorMessage
        val sqlStateField = errorMessage.fields.keys.firstOrNull { "SQLSTATE" == InformationMessage.fieldName(it) }
        return if (sqlStateField === null) null else errorMessage.fields[sqlStateField]
    }
```

Will it be possible to add a function to `GenericDatabaseException` to get the SQLSTATE and other relevant info? Another option is to make the fields in `InformationMessage` public, but his is less ideal IMHO.

Thank you!

**Comment by oshai** [comment]
It's possible to add a similar function to GenericDatabaseException. Would you like to create a PR?

**Comment by afbarbaro** [comment]
> It's possible to add a similar function to GenericDatabaseException. Would you like to create a PR?

Awesome, yes, I'll open a PR and reference this issue.  Thank you!

**Comment by oshai** [comment]
@afbarbaro - any update on this?
