### ISSUE TITLE
Support for high availability

### ISSUE THREAD

**Issue by kevin70** [jasync-sql/jasync-sql#28]
I like jasync-sql very much.
But it does not support master/slave and read/write at present. I can't use it in the production environment.
Is there a support plan behind?
Thanks.

**Comment by oshai** [comment]
Can you please explain what you mean? the way to go with a master/slave approach is usually to create separate connection pools for read and write ops.

**Comment by kevin70** [comment]
Like this.
```
jdbc:mysql:replication://[master host][:port],[slave host 1][:port][,[slave host 2][:port]]...[/[database]] »
[?propertyName1=propertyValue1[&propertyName2=propertyValue2]...]
```

**Comment by oshai** [comment]
I don't see such support coming in the near future. It is still possible to use master/slave with separate pools and we actually do that.

**Comment by kevin70** [comment]
ok, thinks.
