### ISSUE TITLE
Do not support special query name like 'group'

### ISSUE THREAD

**Issue by olive-oasis** [jasync-sql/jasync-sql#291]
I used the column name 'group' and the query was failed because the 'group' is the reserved word.
We should change the "group" to "\`group\`".

**Comment by oshai** [comment]
IIUC this is a DB feature and not related to the driver itself. you can try the suggestions here: https://stackoverflow.com/questions/54479920/how-to-use-a-reserved-word-in-sql-as-a-table-name

If that still doesn't work please provide more info like the error stacktrace, table schema (and what db) and the query you try to execute.
