### ISSUE TITLE
Unknown authentication method

### ISSUE THREAD

**Issue by Tuegor** [jasync-sql/jasync-sql#297]
Hey there!
I've come across the same issue that is described in #117 and in a later one. That is when I send a request to MySQL from my service I receive this crappy message "Unknown authentication method -> 'caching_sha2_password'". I've applied the solution offered in that issue and I've looked up in the docs what it means. I've checked the mysqld variables values in the command line and made sure that that variable's value was updated from that options file. Everything looks fine except the fact that it doesn't work! The service still shows that crap, which means your driver doesn't take this variable from mysqld as it's supposed to, but from somewhere else. What's going on?

**Comment by oshai** [comment]
you can see how we configured the server for tests (with docker) here: https://github.com/jasync-sql/jasync-sql/blob/6de042b540b65ea76dbc9dd96e31657969ec322a/samples/dockers/mysql/docker-compose.yml

It might assist.

There are some attempts to support newer auth methods, latest can be seen here: https://github.com/systriver/jasync-sql/tree/caching_sha2

PR is welcome.

**Comment by Tuegor** [comment]
Well, it didn't assist, cause it does the same that I did - sets that variable's value. Is there a log of some kind that I can look at and see what's going on under the hood?

**Comment by Tuegor** [comment]
After 3 wasted days of trying everything thinkable with MySQL I tried switching to db in Docker and it worked. But when I switched back to Windows db, it worked as well! What the?

**Comment by renshujian** [comment]
I can add a new user identified with mysql_native_password, but can't modify server default_authentication_plugin.

According to [doc](https://dev.mysql.com/doc/refman/8.0/en/pluggable-authentication.html#pluggable-authentication-connector-writing), **client can fall back to its own default plugin in case of failure to load the default plugin specified by the server**.

if [HandshakeResponseEncoder](https://github.com/jasync-sql/jasync-sql/blob/172d9a773536bb0fb172f5885a7bf9e16a0e7d26/mysql-async/src/main/java/com/github/jasync/sql/db/mysql/encoder/HandshakeResponseEncoder.kt#L33) don't throw, we can connect to mysql 8 without server default change.

**Comment by oshai** [comment]
@renshujian a PR is welcome if you want to do so.

**Comment by czp3009** [comment]
@oshai  I have some confusion about not supporting caching_sha2_password. Is this because r2dbc does not allow it or just because of the lack of PR?

**Comment by oshai** [comment]
> @oshai I have some confusion about not supporting caching_sha2_password. Is this because r2dbc does not allow it or just because of the lack of PR?

there is no support for `caching_sha2_password` in the jasync-mysql driver itself, not the r2dbc wrapper. So the PR should be for the driver.

It was asked few times before (you can see in https://github.com/jasync-sql/jasync-sql/search?q=caching_sha2_password&type=issues) and mostly looking for contribution for that, as I don't have plans to implement it at the moment.

**Comment by czp3009** [comment]
@oshai Thank you very much for your patient response!

**Comment by KarboniteKream** [comment]
I can work on adding support for `caching_sha2_password`

**Comment by oshai** [comment]
> I can work on adding support for `caching_sha2_password`

Thanks!
