### ISSUE TITLE
how to change log level in java 

### ISSUE THREAD

**Issue by GlassyYang** [jasync-sql/jasync-sql#298]
I tried to use `jasync-sql` in my maven project, but it output too many messages. How can I change the log level of `jasync-sql`? please give me some more detailed information. The answer  of   [F&Q](https://github.com/jasync-sql/jasync-sql/wiki/FAQ#q-how-can-i-see-the-message-begin-sent-and-received-between-the-driver-and-the-server) is not so clear.

**Comment by oshai** [comment]
Not sure what logging framework you're using, but changing `com.github.jasync` level to warn should reduce logs.

**Comment by GlassyYang** [comment]
I have disabled `jasync-mysql`'s log according to your advice. Thank you very much.
