### ISSUE TITLE
Processing freezes for GET requests

### ISSUE THREAD

**Issue by Tuegor** [jasync-sql/jasync-sql#299]
Hello!
Here comes a problem again. I had to implement Persistable with my entity class so that inserting new entities with existing ids via POST worked. And after that the GET requests working before cause a service freeze, that is no response and no console output. Can you explain it?

**Comment by oshai** [comment]
Doesn't sounds like it's an issue related to the driver, which is only connecting to db. The driver has no http calls at all (only tcp).
