### ISSUE TITLE
Query that selects Spatial type will crash 

### ISSUE THREAD

**Issue by inmyth** [jasync-sql/jasync-sql#30]
Hi and thank you for continuing the sql async library. 
So I found that any query that fetches Spatial data type will cause this error
```
java.lang.UnsupportedOperationException: An operation is not implemented: not implemenetd for 255
```
I assume this also happens to any blob data. Right now the only workaround is to avoid selecting the column.

**Comment by oshai** [comment]
Blobs are supported but spatial types aren't. you can see all the supported types in the relevant readme. for MySQL it is here: https://github.com/jasync-sql/jasync-sql/blob/master/mysql-async/README.md
I don't know what is required to support those types (for example what type is it in Java). Also, can you provide a stacktrace? is it mysql or postgresql?

**Comment by inmyth** [comment]
Sorry I forgot about that page. So this is on mysql. The single line above is the only stacktrace I get. To reproduce it, simply handle the future from `sendPreparedStatement` with sql selecting a spatial data column.  

But after researching a bit, I think spatial type should not be supported natively. It's too complex. The best way to fetch such data is to wrap it with `astext()` where it will be returned as string.

**Comment by oshai** [comment]
Thats a good idea, I will add that to the wiki.

**Comment by oshai** [comment]
wiki was updated: https://github.com/jasync-sql/jasync-sql/wiki/FAQ#q-are-spatial-types-supported
