### ISSUE TITLE
Netty dependency classpath issue

### ISSUE THREAD

**Issue by inmyth** [jasync-sql/jasync-sql#31]
Not necessarily an issue of this library but there seems to be some dependency inside that uses netty-all. This artifact has classpath issues (see https://github.com/netty/netty/issues/4671) that conflict with other netty modules. This can become a problem when packaging a fat jar.
In my project I resolved it by excluding netty-all. But it looks like this library doesn't need it either.

**Comment by oshai** [comment]
What version of jasync are you using?
In version 0.8.41 the dependecy were fixed. Right now we also have artifacts for both netty 4.0 and 4.1. More details on the change log: https://github.com/jasync-sql/jasync-sql/blob/master/CHANGELOG.md

**Comment by inmyth** [comment]
You're right. I was still using 0.8.34 . I upgraded to 0.8.41 and the project can be built without any classpath conflict. Thanks again.
