### ISSUE TITLE
r2dbc interface unable to close prepared statement

### ISSUE THREAD

**Issue by knuclechan** [jasync-sql/jasync-sql#312]
I've found a previous [thread](https://github.com/jasync-sql/jasync-sql/issues/244) of the same issue, but it is unhandled and closed. However, it is a very serious issue that should be handled. I've spend a lot of time of investigating why the mysql server crash periodically, and it is not easy to find out it is due to unclosed prepared statements. I don't think I am the only one. It is very likely to happen if you are using connection pool and have queries that have arbitrary number of items in an `in` condition.

I think the library should provide a mean for the user to specify if the prepared statement should be close or not. If the library are not going to provide such a choice. Please just set the default to close the prepared statement, instead of setting up a trap that crashes production mysql server after up for some weeks and potentially corrupting the data.

I would suggest:
1. Add a configuration to connectionFactory to config the default behavior.
2. Allow setting the behavior per query in the r2dbc.spi.Statement object.
3. Better set the default behavior to close the prepared statement

**Comment by oshai** [comment]
I see that [r2dbc](https://github.com/r2dbc/r2dbc-pool) now has `maxLifeTime`, so one option is using it.   

The driver has support to close prepared statement, see #82, but I think r2dbc don't have such api.  

So one approach would be to open an issue in `r2dbc.spi`.

What we can do in the driver is having the behavior controlled via env prop (ie: `-DautocloseStatements=true`).

**Comment by oshai** [comment]
Added in 2.1.9, thanks!
