### ISSUE TITLE
More samples in the sample catalog version is too old 1.0 vs 2.0 connection database 

### ISSUE THREAD

**Issue by Dukro** [jasync-sql/jasync-sql#313]
### How to use the latest code in the 2.0 repository
**connection: Connection = ConnectionPool(
      MySQLConnectionFactory(Configuration(
          username = "username",
          password = "password",
          host = "localhost.com",
          port = 3306,
          database = "test"
      )), poolConfiguration)constructor ConnectionPool<T : ConcreteConnection>
(
factory: ObjectFactory<T>,configuration: ConnectionPoolConfiguration)**

**Comment by oshai** [comment]
Can you please provide more info about the issue?

**Comment by Dukro** [comment]
More samples in the sample catalog using the library version is too low，Version 2.1.1 Connection Database Code Template 
        <dependency>
            <groupId>com.github.jasync-sql</groupId>
            <artifactId>jasync-postgresql</artifactId>
            <version>0.8.31  or 2.1.1 </version>
        </dependency>
// factory: ObjectFactory,configuration: ConnectionPoolConfiguration)
connection: Connection = ConnectionPool(
MySQLConnectionFactory(Configuration(
username = "username",
password = "password",
host = "localhost.com",
port = 3306,
database = "test"
)), poolConfiguration)constructor ConnectionPool
(

**Comment by oshai** [comment]
would you like to create a pull request to fix that?

**Comment by Dukro** [comment]
Yes, we would like to update the complete examples in jasync-mysql-example and jasync-postgresql-example.
More samples in the sample catalog code template for the latest version 2.1.1

**Comment by dhaller-neurio** [comment]
The connection in the postgres example gives a type check error: 

https://github.com/jasync-sql/jasync-postgresql-example/blob/c79d9ee0501241753c8f526053a58ba35ea00410/src/main/java/com/github/jasync/mysql/example/MainJava.java#L43

**Comment by oshai** [comment]
would you like to create a pull request so I will check it?

**Comment by oshai** [comment]
Examples Updated.
