### ISSUE TITLE
Needs guide configuring ConnectionFactory Bean manually

### ISSUE THREAD

**Issue by kworkbee** [jasync-sql/jasync-sql#333]
I'm just manually registering beans related to R2dbc for the project I'm currently working on.

I just found that ConnectionFactory Bean is not using `ActorBasedObjectPool`, so I'd like to modify the configuration, is there any guideline for this?

This question was asked to confirm #308. Thanks :)

**Comment by oshai** [comment]
R2DBC can't work with jasync connection pool (ActorBasedObjectPool), only with it's own pool, because the r2dbc spi is only for connections, not pools. So r2dbc creates mysql connection directly. Pooling is done only with https://github.com/r2dbc/r2dbc-pool.
