### ISSUE TITLE
Missing R2dbcExceptions mapping 

### ISSUE THREAD

**Issue by pearlgupta2000** [jasync-sql/jasync-sql#350]
In commit: [https://github.com/jasync-sql/jasync-sql/pull/116/files#diff-48ac27ec5f7ffa2729c94453b580b09eed8a1a59e32d3836d52d83ba0e91d6b5](https://github.com/jasync-sql/jasync-sql/pull/116/files#diff-48ac27ec5f7ffa2729c94453b580b09eed8a1a59e32d3836d52d83ba0e91d6b5), file: r2dbc-mysql/src/main/java/JasyncStatement.kt,

If MySQLException is catched, R2dbcTransientExceptions like R2dbcTimeoutException, R2dbcRollbackException and R2dbcTransientResourceException are not mapped properly because of which each of them falls in JasyncDatabaseException.

Because of which, springframework.r2dbc (org.springframework:spring-r2dbc v5.3.19) always throws them as UncategorizedR2dbcException, whereas in ideal case it should be throwing them as QueryTimeoutException, ConcurrencyFailureException and TransientDataAccessResourceException respectively.

**Comment by oshai** [comment]
Hi, thanks for reporting - would you like to suggest a fix / test for that?

**Comment by pearlgupta2000** [comment]
Yes for fixing this, R2dbcTransientExceptions like like R2dbcTimeoutException, R2dbcRollbackException and R2dbcTransientResourceException should be mapped/handled here : [https://github.com/jasync-sql/jasync-sql/blob/cb42f3f88cadf80e07d6b358c8853e1650482070/r2dbc-mysql/src/main/java/JasyncStatement.kt#L107](https://github.com/jasync-sql/jasync-sql/blob/cb42f3f88cadf80e07d6b358c8853e1650482070/r2dbc-mysql/src/main/java/JasyncStatement.kt#L107).

`errorMessage.errorCode == 3024 -> R2dbcTimeoutException(
                                errorMessage.errorMessage,
                                errorMessage.sqlState,
                                errorMessage.errorCode,
                                throwable
                            )`
Similarly for others like R2dbcRollbackException, R2dbcTransientResourceException, R2dbcNonTransientResourceException and R2dbcDataIntegrityViolationException. 

For errorcodes reference : [https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html)

Below is the screenshot of how springframework.r2dbc (org.springframework:spring-r2dbc v5.3.19) handles and converts the R2dbcExceptions after being thrown from jasync r2dbc.
<img width="960" alt="Screenshot 2023-01-05 at 1 50 02 PM" src="https://user-images.githubusercontent.com/44175292/210943018-73044316-d0f4-40cb-ae6c-f10ba651a0d6.png">

**Comment by oshai** [comment]
Take a look at https://github.com/jasync-sql/jasync-sql/pull/355 and let me know if you think other cases are needed and if that looks good.

**Comment by princensit** [comment]
@oshai This PR #355 would only handle couple of error codes, and may not be exhaustive considering https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html. Do we have better approach? 

I believe we need to create MySQL Error mapping as per https://github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/core-api/java/com/mysql/cj/exceptions/MysqlErrorNumbers.java and https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-error-sqlstates.html

**Comment by oshai** [comment]
Ok, I can try that. If someone else wants to contribute this is welcome.

**Comment by oshai** [comment]
I added codes of exceptions. Since there are many codes future contribution is welcome (to map them).

**Comment by oshai** [comment]
Added to jasync 2.1.11

**Comment by pearlgupta2000** [comment]
Can u add these changes to jasync 2.0.8 version

**Comment by oshai** [comment]
> Can u add these changes to jasync 2.0.8 version

As described [here](https://github.com/jasync-sql/jasync-sql/issues/344#issuecomment-1379896884) you're welcome to create a PR to branch r2dbc-pre-ga and I will merge and release it.

Closing this issue with PR #355. Additional error codes support contribution is welcome.
