### ISSUE TITLE
R2dbc unimplemented api 

### ISSUE THREAD

**Issue by dave08** [jasync-sql/jasync-sql#351]
There seems to be some api not implemented: https://github.com/jasync-sql/jasync-sql/blob/2.1.8/r2dbc-mysql/src/main/java/JasyncResult.kt#L45 which prevents libraries like Komapper to support jasync r2dbc's driver.

**Comment by oshai** [comment]
Thanks for reporting. For reference spi is here: https://javadoc.io/doc/io.r2dbc/r2dbc-spi/latest/index.html

Here is an example impl from postgres: https://github.com/pgjdbc/r2dbc-postgresql/blob/6d2c1a84a7de8e0ecc183c1a4195b4a5bc01ab75/src/main/java/io/r2dbc/postgresql/PostgresqlResult.java

**Comment by oshai** [comment]
@mp911de can you please assist in finding resources how to implement the 1.0 filter/flatmap?

Here is what I figured out (and correct me  if I am wrong of course):
- both methods expect to work on a "segment" which IIUC has different type for different response? I found [this](https://assets.ctfassets.net/oxjq45e8ilak/5qfKgapWWIuIqDXVteQJEW/b226f99ad6593751fc3dd2194c9026a2/Mark_Paluch_On_the_way_to_Reactive_Relational_Database_Connectivity_1.0_2021_10_21_09_57_18.pdf)
- for jasync response we eagerly collect all the data in advance, so maybe filtering by row count / rows etc' should be straight forward? can we just provide some kind of filtered view on the result, and then implement a similar idea for flatmap?
- can we somehow reuse the original map functions by just implementing flatter to use both as flatmap?

**Comment by mp911de** [comment]
`flatMap` and `filter` are part of the segment API. Basically, a `Row` is already a segment. Segments are wrappers around messages, update counters and rows. That API allows to filter the segments that a user wants to consume. `flatMap` is a `map` that returns a `Publisher`.

The idea that drives all this is that we allow stream processing of the database responses. 

Take a look at https://github.com/pgjdbc/r2dbc-postgresql/blob/main/src/main/java/io/r2dbc/postgresql/PostgresqlSegmentResult.java#L151-L207, the implementations aren't that different.

**Comment by oshai** [comment]
So IIUC if we take filter for example and the case that the filter is on `RowSegment`, then I should wrap each of my rows with JasyncRow, and then wrap it with RowSegment (or it should just inherit that) and then apply the predicate on that?

Is that the right direction?

The only subtype which is not exactly clear to me is `OutSegment`. What does it stands for?

**Comment by mp911de** [comment]
For filtering, the elements would be filtered for the returned `Result` object. Same goes for messages, that a user wants to include/remove from the final `Result`.

`OutSegment` is for databases that support `OUT` variables for stored procedures (e.g. SQL Server, Oracle). I'm not sure how/whether MySQL supports stored procedures OUT variables. Postgres uses rows to return OUT variables.

**Comment by oshai** [comment]
@mp911de I created a PR in #356. I will be glad if you can take a look.

**Comment by oshai** [comment]
Added in 2.1.11
