### ISSUE TITLE
Incorrect argument type to variable 'innodb_lock_wait_timeout'

### ISSUE THREAD

**Issue by kwidjaja1312** [jasync-sql/jasync-sql#367]
Hi Team,

I found a bug during the transaction creation process which was happened when we set the lock timeout value.

My stacks is Spring Boot with Spring Webflux and Jasync R2DBC MySQL. When i set the `timeout` value on the `@Transactional(...)` on the Controller method, i got this error below:

```
ErrorMessage(errorCode=1232, sqlState=#42000, errorMessage=Incorrect argument type to variable 'innodb_lock_wait_timeout'
```

I found that during the debugging that the code does not extract/transform the `Duration` into a number at this file:

File: **JasyncClientConnection.kt**

```
definition.getAttribute(TransactionDefinition.LOCK_WAIT_TIMEOUT)?.let { timeout ->
  future = future.flatMap { jasyncConnection.sendQuery("SET innodb_lock_wait_timeout=$timeout") } // This $timeout needs to be in number instead of 'P15S` or 'P10M' for example.
}
```

**Comment by oshai** [comment]
Thanks! according to the docs the unit for this is seconds: https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_lock_wait_timeout

I am creating a fix.

**Comment by kwidjaja1312** [comment]
> Thanks! according to the docs the unit for this is seconds: https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_lock_wait_timeout
> 
> I am creating a fix.

@oshai Thank you so much for such a prompt response. 

PS: This is my first time using this driver as i had to find the replacement for `r2dbc-mysql`.

**Comment by kwidjaja1312** [comment]
Hi @oshai, Are you going to create release `2.1.4` for this?

**Comment by oshai** [comment]
I release 2.1.14 now with the fix, should be available soon.
