### ISSUE TITLE
Duplicate entry on a table mapped to generic exception

### ISSUE THREAD

**Issue by kwidjaja1312** [jasync-sql/jasync-sql#375]
Added MySQL Error 1062 mapping to R2dbcDataIntegrityViolationException as reported at https://gitter.im/jasync-sql/support?at=63c9661ec47d5810629a262a.

My project depends on this exception heavily hence need this error mapped to said exception above. Otherwise i need to change pretty lots of code to handle the `UncaughtDatabaseException` from the Spring Data R2DBC itself.

PR has been created: https://github.com/jasync-sql/jasync-sql/pull/374

**Comment by oshai** [comment]
Can we close this one?
