### ISSUE TITLE
Error 1568 - #25001 - Transaction characteristics can't be changed while a transaction is in progress

### ISSUE THREAD

**Issue by turnik** [jasync-sql/jasync-sql#380]
Hi there.

Our team faced issue `com.github.jasync.sql.db.mysql.exceptions.MySQLException: Error 1568 - #25001 - Transaction characteristics can't be changed while a transaction is in progress` 
when using transaction isolation level READ_COMMITED, defined by transaction definition (not MySQL property)

Our research shows that driver sends the following commands to the database
```sql
START TRANSACTION;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
```

According to MySQL documentation, this order is possible only with GLOBAL or SESSION keyword.
The correct order of commands looks like
```sql
SET autocommit = 0;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
```

This issue affects all Spring Boot 3 projects with R2DBC version > 0.9.0 and JAsync MySQL driver.
Fix in https://github.com/jasync-sql/jasync-sql/pull/379

**Comment by oshai** [comment]
Can we close the issue?

**Comment by turnik** [comment]
For sure

**Comment by oshai** [comment]
Thanks!
