### ISSUE TITLE
MySQL- unable to use parameters in LIKE statements

### ISSUE THREAD

**Issue by YaduAhuja** [jasync-sql/jasync-sql#382]
I recently experienced an issue when using parameters in LIKE statements with MySQL where the prepared statements does not works correctly. I think this is because jasync ignores the ? operator when it is enclosed in single quotes. 

If we don't enclose ? in single quotes then we get syntax exception.

Is there something I am doing wrong. 

I am attaching the project zip. can you please verify what is the issue. 

[jasynctest.zip](https://github.com/jasync-sql/jasync-sql/files/10776683/jasynctest.zip)

**Comment by oshai** [comment]
Prepares statements are sent to server as is (jasync is not doing any parsing).  
Can you please share here examples for the queries you mentioned?

**Comment by oshai** [comment]
I see query like:
```
List<String> values = List.of("English");
        var result = connectionPool.sendPreparedStatement("SELECT * FROM USER WHERE LANGUAGE LIKE ?", values).get();
```

**Comment by oshai** [comment]
Can you add here the error you see?

**Comment by YaduAhuja** [comment]
Suppose we execute both these statements in current dataset the result is not same but it should be same.

`
var resultNormal = connectionPool.sendPreparedStatement("SELECT * FROM USER WHERE LANGUAGE LIKE ?", values).get();
var result = connectionPool.sendPreparedStatement("SELECT * FROM USER WHERE LANGUAGE LIKE '%?%'", values).get();
`

**Comment by oshai** [comment]
The second query has an error? what is the error message?

**Comment by YaduAhuja** [comment]
Nevermind found the error it was in the sql query itself.

Thanks for the help.
