### ISSUE TITLE
Using reactive libraries with coroutines

### ISSUE THREAD

**Issue by dxxvi** [jasync-sql/jasync-sql#386]
Questions:

1. Does it make sense to use reactive libraries (for example, this library) with kotlin coroutines?
2. What issues might I have if I use the blocking jdbc in a kotlin `suspend fun`?

**Comment by oshai** [comment]
Hi,
There is already support for coroutines, see: https://github.com/jasync-sql/jasync-sql/wiki/Kotlin-API#kotlin-coroutines-support.

This library is not a blocking jdbc, so the question in 2 is not clear to me.
