### ISSUE TITLE
New Relic cannot find Jasync-MySQL operation

### ISSUE THREAD

**Issue by adrianaden** [jasync-sql/jasync-sql#387]
Hello I'm currently using Jasync-MySQL 2.0.9 to my Spring Boot Webflux project, the result is really great, but when I open Databases Monitoring in New Relic, they said if they couldn't find database operations, do you have any suggestion the Jasync-MySQL version that I need to use?

![image](https://user-images.githubusercontent.com/23077760/227981948-7ba1156c-c3d0-4be6-b550-97221de33188.png)

```
<dependency>
    <groupId>com.github.jasync-sql</groupId>
    <artifactId>jasync-r2dbc-mysql</artifactId>
    <version>2.0.9</version>
</dependency>
```

other dependencies
```
Java: 11
Spring Boot: 2.4.4
New Relic Agent: 7.11
```

thank you ❤️

**Comment by oshai** [comment]
I am not so familiar with new relic. Is it measuring on the database side or client side?
Maybe it is connected to jdbc somehow?

**Comment by oshai** [comment]
Please reopen if anything still needed.
