### ISSUE TITLE
ConnectionStillRunningQueryException: <<mysql-connection-1>> - There is a query still being run here - race -> true

### ISSUE THREAD

**Issue by SynkovAndrew** [jasync-sql/jasync-sql#388]
Hi!

I'm using jasync-mysql-2.1.23, spring boot 3.0.5, mysql 8. 

When there is any kind of zip() operation like Mono.zip used with transaction, the following error appears:

com.github.jasync.sql.db.exceptions.ConnectionStillRunningQueryException: <<mysql-connection-1>> - There is a query still being run here - race -> true

If zip() is not used or transaction is not used there is no error.

I thought the issue has been fixed there https://github.com/jasync-sql/jasync-sql/issues/255, but seems like not.

**Comment by oshai** [comment]
Can you please provide a test case similar to: https://github.com/jasync-sql/jasync-sql/blob/master/r2dbc-mysql/src/test/java/com/github/jasync/r2dbc/mysql/integ/R2dbcTransactionIntegrationTest.kt

That will help debug the issue.

**Comment by SynkovAndrew** [comment]
Simple test to reproduce issue:

```
@SpringBootTest
class Test @Autowired constructor(
    private val r2dbcEntityTemplate: R2dbcEntityTemplate,
    private val transactionManager: ReactiveTransactionManager
) {

    @Test
    fun test() {
        val required = TransactionalOperator.create(transactionManager)

        r2dbcEntityTemplate.databaseClient.sql("CREATE TABLE A(a VARCHAR(255) NOT NULL)").then().block()
        r2dbcEntityTemplate.databaseClient.sql("CREATE TABLE B(b VARCHAR(255) NOT NULL)").then().block()

        Mono
            .zip(
                r2dbcEntityTemplate.databaseClient.sql("INSERT INTO A VALUES ('aaaa')").then(),
                r2dbcEntityTemplate.databaseClient.sql("INSERT INTO B VALUES ('bbbb')").then()
            )
            .`as`(required::transactional)
            .subscribeOn(Schedulers.boundedElastic())
            .test()
            .verifyComplete()
    }
}
```

Does this test case suits you?

**Comment by oshai** [comment]
I will take a look when I have some time.

**Comment by zhuangzibin** [comment]
I'm having the same problem. I was two select statements, using 
mono1.zipwith(mono2) ,Mono.zip(mono1, mono2)
When the first statement reports an error, it displays the second statement exception

**Comment by oshai** [comment]
Altough async, queries cannot run concurrently on the same connection. I think you must do map / flat map between queries and only later process results.

**Comment by oshai** [comment]
There are two options I can think of:
- collecting the data (into collections) before the zip (one after another).
- run each publisher on a separate connection.

**Comment by zhuangzibin** [comment]
> @oshai因此，如果参数是对数据库运行操作的发布者，则不可能使用 zip 函数？

If you use <@Transactional(rollbackFor = Exception.class)> you can't use Mono.zip
I use r2dbc-postgresql without this problem, but I still can't understand why I can't use <Mono.zip> <Mono.zipWith>

**Comment by oshai** [comment]
Let me try to clarify:
```
Mono
            .zip(
                r2dbcEntityTemplate.databaseClient.sql("INSERT INTO A VALUES ('aaaa')").then(),
                r2dbcEntityTemplate.databaseClient.sql("INSERT INTO B VALUES ('bbbb')").then()
            )
```
Those 2 sql are not blocking and are running concurrently on the same connection. 

This requires multiplexing and is not supported in jasync.

What I suggest is to use `map` on the first mono, then execute second query and return a pair of result (it will be a mono of Pair). Does that makes sense?

**Comment by oshai** [comment]
Closing the issue. Please reopen if anything else needed.
