### ISSUE TITLE
Incompatiblity with Spring Boot 2.7.10

### ISSUE THREAD

**Issue by martinformi** [jasync-sql/jasync-sql#389]
Not sure where to address this issue, but I am getting casting exception at;

```
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at java.base/java.util.stream.Collectors.lambda$summingInt$19(Collectors.java:681)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Assembly trace from producer [reactor.core.publisher.MonoStreamCollector] :
	reactor.core.publisher.Flux.collect
	org.springframework.r2dbc.core.DefaultDatabaseClient.sumRowsUpdated(DefaultDatabaseClient.java:193)
```

when doing:

```
roTemplate.databaseClient.sql("delete from zzz where 1=1").await()
```

It looks the exception occurs when collecting the list. 
```
	private static Mono<Integer> sumRowsUpdated(Function<Connection, Flux<Result>> resultFunction, Connection it) {
		return resultFunction.apply(it)
				.flatMap(Result::getRowsUpdated)
				.collect(Collectors.summingInt(Integer::intValue));
	}
```

Should I forward this issue to spring team or is it jasync related? Please let me know. Thank you.

**jasync-mysql version: 2.1.23**

**Comment by oshai** [comment]
Please try jasync 2.0.9 that should be compatible.

**Comment by martinformi** [comment]
Thing is, with 2.0.9 I am getting https://github.com/jasync-sql/jasync-sql/issues/300 , so only working version is 2.0.8 and Spring Boot 2.6.14.

**Comment by oshai** [comment]
2.0.9 should also work with spring boot 2.6.

There is no supported version for spring boot 2.7 at the moment.

**Comment by mscheong01** [comment]
We decided to upgrade to Springboot 3 because of this issue (https://github.com/jasync-sql/jasync-sql/issues/339)
