### ISSUE TITLE
Executing queries against temporarily offline db always drops the first query

### ISSUE THREAD

**Issue by tlopesPT** [jasync-sql/jasync-sql#392]
Hey 👋 ,

**Context:**
We're using this driver to connect to a PostgreSQL db using the connection pool.
We are testing the driver's behaviour when sending insert queries while the DB is temporarily offline.

**Issue:**
The first insert query always fails with "connection refused", while the remaining succeed if the DB comes back online quickly

**Reproducing:**
1. DB is offline
2. send 100 insert queries (100 is just an example)
3. bring DB online
4. first insert query fails with "connection refused"
5. 99 insert queries executed successfully

I have provided a simple integration test to reproduce this here https://github.com/tlopesPT/jasync-sql-postgres-connection-refused/blob/develop/src/test/java/com/tlopes/PostgreSqlUnavailableIT.java

Can you provide some information on why we're experiencing this behaviour and if there's a way to prevent it?

Thanks

**Comment by oshai** [comment]
Connection refused seems like "work as intended". I think what happens is that the next queries are just waiting for a connection to be available while the first ones get a bad query.  

I think the correct approach is doing a retry on the client side (out of the driver).

**Comment by tlopesPT** [comment]
Thanks for the feedback @oshai, we'll keep this in mind.
