### ISSUE TITLE
Is it possible to specify session variables during connection creation/initialization?

### ISSUE THREAD

**Issue by chandramouli-r** [jasync-sql/jasync-sql#396]
Apologies for asking a question here, but I wanted to make sure I'm on the right track before I raise it as a Github issue.
Is it possible to set Session variables during connection creation similar to what JDBC does as part of the connection URL? From the source code, it seems no specific session variables can be specified.

Alternatively, is there a way in the connection pool configuration to supply a lifecycle hook (onCreate, onEvict) that can be invoked by the pool on connection creation/eviction?

**Comment by oshai** [comment]
Hi,
The way to do that if you're using the driver directly is by overriding connection factory ([mysql](https://github.com/jasync-sql/jasync-sql/blob/master/mysql-async/src/main/java/com/github/jasync/sql/db/mysql/pool/MySQLConnectionFactory.kt)) and providing your own impl when configuring the connection pool.

**Comment by chandramouli-r** [comment]
Thank you. 
Also, for the mysql driver, does it support `useServerPrepStmts` and `cachePrepStmts` currently? A code search gave me no results, but I just wanted to confirm this.

**Comment by oshai** [comment]
the driver has `connection.sendPreparedStatement()`. not sure if you're asking about this or a specific config?

**Comment by oshai** [comment]
Hi, can the issue mark as done?
