### ISSUE TITLE
Using this library there are many examples where methods are not available, methods need to be created, etc

### ISSUE THREAD

**Issue by Dukro** [jasync-sql/jasync-sql#404]
This is the https://github.com/users/Dukro/projects/3 address
Using this library there are many examples where methods 
![微信图片_20230715015052](https://github.com/jasync-sql/jasync-sql/assets/31683631/9f31a816-28ac-49ce-b7f3-fc3fa3131de4)
are not available, methods need to be created, etc
![屏幕截图 2023-07-15 011703](https://github.com/jasync-sql/jasync-sql/assets/31683631/82212671-3dc9-46c9-99ba-a4c3a5a476a7)

**Comment by oshai** [comment]
Try following an example like: 
https://youtu.be/DvO4zLVDkMs

**Comment by Dukro** [comment]
No

**Comment by oshai** [comment]
Updated examples in:
https://github.com/jasync-sql/jasync-mysql-example
https://github.com/jasync-sql/jasync-postgresql-example
