### ISSUE TITLE
Support client side (emulated) prepared statements

### ISSUE THREAD

**Issue by xiongrl** [jasync-sql/jasync-sql#405]
The jdbc mysql driver supports client side prepare. Can we also support client side prepare? This is very helpful to our team. The mysql proxy we use does not support server prepare.

**Comment by oshai** [comment]
Hi,
Supporting that will require developing a parser for the queries.
Then we can parse queries on client side and send a regular statement on each invocation.
At the moment I don't plan to implement that, but contribution is welcome.
