### ISSUE TITLE
<mysql-connection-7> Received an error message -> ErrorMessage(errorCode=1159, sqlState=#08S01, errorMessage=Got timeout reading communication packets)

### ISSUE THREAD

**Issue by stillmoon** [jasync-sql/jasync-sql#406]
use a local mysql server, this is not a network issue, All settings for the program and MySQL are configured by default.

how can i fix it, thanks!

the error message also has:

` ERROR 5806 --- [netty-thread-16] [traceID=] c.g.jasync.sql.db.mysql.MySQLConnection  : <mysql-connection-8> Transport failure 
com.github.jasync.sql.db.exceptions.BufferNotFullyConsumedException: Buffer was not fully consumed by decoder, 21 bytes to read, decoder is AuthenticationSwitchRequestDecoder and message is AuthenticationSwitchRequest
	at com.github.jasync.sql.db.mysql.codec.MySQLFrameDecoder.doDecoding(MySQLFrameDecoder.kt:215) ~[jasync-mysql-2.1.7.jar:na]`

**Comment by oshai** [comment]
looks like an authentication issue. what auth setup are you trying to use?

**Comment by wrq583689440** [comment]
I have configured authentication information in application.yml

((ignore indentation format))
`spring:
      r2dbc:
          url: r2dbc:pool:mysql://${MYSQL_HOST:localhost}:3306/hyperpaas
          username: ${MYSQL_USERNAME:hyperpaas}
          password: ${MYSQL_PASSWORD:hyperpaasmysql}
`

**Comment by wrq583689440** [comment]
I can connect successfully on the terminal, the user and password is right.

**Comment by oshai** [comment]
I was referring to the auth method (and mysql server version). see more details here: https://github.com/jasync-sql/jasync-sql/blob/master/mysql-async/auth-README.md

**Comment by wrq583689440** [comment]
mysql server version is 8.0.31 and auth method is default 'mysql_native_password'.

**Comment by wrq583689440** [comment]
oh, i fix it!
the account auth method is 'caching_sha2_password' but mysql server is 'mysql_native_password'.

I change account auth to mysql_native_password to fix it.

**Comment by wrq583689440** [comment]
Thank you!
