### ISSUE TITLE
named binding is not supported by jasync driver 

### ISSUE THREAD

**Issue by hhtower** [jasync-sql/jasync-sql#416]
when i query then error
"
java.lang.UnsupportedOperationException: named binding is not supported by jasync driver ?=In{Inferred: java.lang.Long}
	at com.github.jasync.r2dbc.mysql.JasyncStatement.bind(JasyncStatement.kt:65)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException.
"

use:
spring boot 3.1.3
jasync-r2dbc-mysql 2.2.4
infobip-spring-data-r2dbc-querydsl-boot-starter 9.0.2

**Comment by minkichoe** [comment]
@hhtower I'm experiencing a similar situation. could you share how you resolved it?
