### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by AnkBurov** [jasync-sql/jasync-sql#45]
Hello. I've just stumbled upon mentioning of this repository in your article about coroutines in backend environment. Great article!

So here is my question: will this project work with MariaDB databases?

**Comment by dougEfresh** [comment]
It should, I'll test it with maria docker to verify.

**Comment by oshai** [comment]
Tests were checked locally against maria db and passed, we will add it to our build when we can.

**Comment by AnkBurov** [comment]
Thanks! I'm closing the issue now.
