### ISSUE TITLE
Fix all compiler warnings and deprecated dependencies

### ISSUE THREAD

**Issue by andy-yx-chen** [jasync-sql/jasync-sql#53]
There are a couple of compile warnings including using deprecated APIs, need to clean them up

**Comment by oshai** [comment]
Thanks for raising that up. I will try to do that when possible.

**Comment by dougEfresh** [comment]
Some of them are from Netty, which is ok because we want to support netty 4.0 and netty 4.1.
Also, netty isn't going to update to version 5 anytime soon, so deprecation will likely never really happen.

**Comment by bytewayio** [comment]
there are also unused fields and variables

**Comment by oshai** [comment]
@dougEfresh - you're right but we should suppress warning on those to make it clear and clean.
@bytewayio - some of the fields are used externally so we should probably suppress that warning specifically on some of them, others can be removed.

**Comment by oshai** [comment]
@andy-yx-chen I completed a cleanup if you see anything more please reopen the issue or PR.
