### ISSUE TITLE
Is it necessary to close connections ? 

### ISSUE THREAD

**Issue by inmyth** [jasync-sql/jasync-sql#57]
So I'm trying to understand how to manage individual connections. 
From the  examples, I see

    connection.sendPreparedStatement("select * ...)

which picks a connection from the pool and executes the query. 
However I also see

    connection.connect().get()

which returns a single connection that can also be chained with sendQuery.
At first I thought with single connection we'd have to close it to return it to the pool. But apparently disconnect method on it would close the pool. It's the same if ConnectionPool. Any disconnect and close would also close the pool. 

Does this mean we don't have to close connections ourselves to return them to the pool ?

**Comment by oshai** [comment]
when using a pool you don't have to connect or release a connection when application is running. just call `connection.connect().get()` on startup and `close` of the pool on shutdown once, and the rest is managed by the connection pool. I also added more details to the wiki to make it more clear:

https://github.com/jasync-sql/jasync-sql/wiki/Configuring-and-Managing-Connections#connections-lifecycle

Let me know if that helps.

**Comment by inmyth** [comment]
Nice. But does `connection.connect().get()` do actually ? I didn't use it but it looks everything is ok.

**Comment by oshai** [comment]
Yes, you are correct. Actually, when using a pool this is not required on startup so you can ignore my comment from above. The connect is only needed if using a connection explicitly.

**Comment by inmyth** [comment]
Ok thanks for the explanation
