### ISSUE TITLE
Not support jpa

### ISSUE THREAD

**Issue by SidneyLann** [jasync-sql/jasync-sql#78]
Does jasync-sql support jpa?

**Comment by oshai** [comment]
Jasync is a database driver so it is more low level than JPA. On top of that can be implemented ORM, JPA and such. At the moment I'm not aware of such implementation.

**Comment by andy-yx-chen** [comment]
@SidneyLann JPA does not have non blocking interface, done.

**Comment by oshai** [comment]
@SidneyLann can we close the issue?

**Comment by SidneyLann** [comment]
yes, should implement async version of jpa in another place.

**Comment by oshai** [comment]
ok, in case you do that let us know so we will reference that on this repo.
