### ISSUE TITLE
It looks like the latest release does not show up in jcenter

### ISSUE THREAD

**Issue by andy-yx-chen** [jasync-sql/jasync-sql#91]
maven is not able to see the latest release in the public

**Comment by oshai** [comment]
Are you referring 0.8.68?

**Comment by andy-yx-chen** [comment]
yea, I am trying to update vertx-mysql

**Comment by oshai** [comment]
I don't mind releasing another version if it helps, but I can see it in here: https://bintray.com/bintray/jcenter and also managed to download it.

**Comment by andy-yx-chen** [comment]
okay, let me try it out

**Comment by oshai** [comment]
I also released 0.8.69. you can try that.

**Comment by andy-yx-chen** [comment]
Okay, thanks!
